export const rawData = [
  {
    kind: "youtube#searchResult",
    etag: "2JasxlistNqsMCdiiuDLJPErIcU",
    id: {
      kind: "youtube#video",
      videoId: "wxt77goIlXo",
    },
    snippet: {
      publishedAt: "2024-10-12T17:07:09Z",
      channelId: "UCq29tGmaqaKhChzbIHHNyqQ",
      title:
        "EASY ORANGE DRAWING, #easy #easydrawing #beginners #painting #artandcraft #art #drawingideas #diy",
      description:
        "EASY ORANGE DRAWING, #easy #easydrawing #beginners #painting #artandcraft #art #drawingideas #diy.",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/wxt77goIlXo/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/wxt77goIlXo/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/wxt77goIlXo/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "try it out",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T17:07:09Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "naEynmBsO1SYDASsn9fI4Mvi3pM",
    id: {
      kind: "youtube#video",
      videoId: "wWmAmGQdOu0",
    },
    snippet: {
      publishedAt: "2024-10-12T14:00:50Z",
      channelId: "UCw1lCaqwNbS34e235eVEyWQ",
      title: "Solved a Rubik&#39;s Cube color Orange",
      description: "",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/wWmAmGQdOu0/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/wWmAmGQdOu0/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/wWmAmGQdOu0/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "The Fighter",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T14:00:50Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "L7V3JMDIb8oLVMf_r0Tt-bu3pC4",
    id: {
      kind: "youtube#video",
      videoId: "oSfFfuuGxYI",
    },
    snippet: {
      publishedAt: "2024-10-12T13:42:13Z",
      channelId: "UCD8yoDPxz0id8OgGCRPiVIw",
      title: "ഇത്രയും ചെറിയ മരത്തിൽ orange ഇതുപോലെ കായിക്കുമോ? ടിപ്സ്.",
      description:
        "ഇത്രയും ചെറിയ മരത്തിൽ orange ഇതുപോലെ കായിക്കുമോ? ടിപ്സ്. Can an orange bear ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/oSfFfuuGxYI/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/oSfFfuuGxYI/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/oSfFfuuGxYI/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Rose Garden",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T13:42:13Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "t09cx-DC0QGHC8cvClLHFXcQj9c",
    id: {
      kind: "youtube#video",
      videoId: "wZGKufDhm70",
    },
    snippet: {
      publishedAt: "2024-10-12T13:03:16Z",
      channelId: "UCBfDfKIepnqC5pnWCAKikSg",
      title: "Orange ka real colour       #facts #factinhindi #factshorts",
      description: "Orange ka real colour #facts #factinhindi #factshorts.",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/wZGKufDhm70/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/wZGKufDhm70/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/wZGKufDhm70/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "TechMeraz ",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T13:03:16Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "2uT0VRrfryJ17oCsXBxWdBahIjM",
    id: {
      kind: "youtube#video",
      videoId: "qbSfTazMxkI",
    },
    snippet: {
      publishedAt: "2024-10-12T12:50:42Z",
      channelId: "UCBAVeOwX9GupXekfAp0J1oA",
      title: "If You Eat 1 Orange Every Day This Is What Happens To Your Body",
      description:
        "If You Eat 1 Orange Every Day This Is What Happens To Your Body #oranges #keto #ketodiet #weightloss #ketolifestyle ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/qbSfTazMxkI/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/qbSfTazMxkI/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/qbSfTazMxkI/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Diet Zone",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T12:50:42Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "DBcFlpICrzTRoONa4AywqzJTigA",
    id: {
      kind: "youtube#video",
      videoId: "2pVpngmH9bc",
    },
    snippet: {
      publishedAt: "2024-10-12T12:33:45Z",
      channelId: "UCWnnmlIKF975UuXGjc0TWmQ",
      title:
        "Get Glowing Skin with ORANGE PEEL! (Vitamin C Serum Hack) [2024]#shorts",
      description:
        "Unlock the secret to radiant, glowing skin with our latest DIY hack using orange peel! In this video, we'll show you how to create a ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/2pVpngmH9bc/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/2pVpngmH9bc/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/2pVpngmH9bc/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "The Ai Tara",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T12:33:45Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "2OrQT8DM99NY6jRowXCukRIGy98",
    id: {
      kind: "youtube#video",
      videoId: "zNK2da8K3ZM",
    },
    snippet: {
      publishedAt: "2024-10-12T12:01:16Z",
      channelId: "UC3S6nIDGJ5OtpC-mbvFA8Ew",
      title: "I Maxed out the Lavaloon Puppet",
      description:
        "New Halloween event in 2024. New hero equipment the Lavaloon puppet. Witch Golem, Barcher, Hog Wizard, Ice Minion and ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/zNK2da8K3ZM/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/zNK2da8K3ZM/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/zNK2da8K3ZM/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Orange Juice Gaming",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T12:01:16Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "vWtlNQok2IDchyq_9XMRzZtsMro",
    id: {
      kind: "youtube#video",
      videoId: "5u8UXyW7fDA",
    },
    snippet: {
      publishedAt: "2024-10-12T11:15:36Z",
      channelId: "UCm3cpXx3A7Lb3GgkcGYUV7g",
      title:
        "Orange peel home made face mask😍😍#trendingshorts #skincare #skincaretips #homemade #beauty",
      description:
        "Orange peel home made face mask    #trendingshorts #skincare #skincaretips #homemade #beauty.",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/5u8UXyW7fDA/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/5u8UXyW7fDA/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/5u8UXyW7fDA/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Anjum",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T11:15:36Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "1aHnDzaUL0rdTDpwCQBCERby67c",
    id: {
      kind: "youtube#video",
      videoId: "hFGhguimKHg",
    },
    snippet: {
      publishedAt: "2024-10-12T10:24:57Z",
      channelId: "UCCl62oBQfjUAjBg3AKYt7Ww",
      title: "how to draw an orange - Part 2 drawing fruits",
      description: "",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/hFGhguimKHg/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/hFGhguimKHg/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/hFGhguimKHg/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "colouring and drawing ",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T10:24:57Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "-yVeJBW1CAeAkjirMKrVeTo21vA",
    id: {
      kind: "youtube#video",
      videoId: "Ytsy15xLtgc",
    },
    snippet: {
      publishedAt: "2024-10-12T07:56:26Z",
      channelId: "UCYRJN1hoKPJ0GuQy7m5tWSw",
      title:
        "ORANGE QUILL |  SPIRITBORN RANK 1 PUSH | 150+ Beta Hours | GOBLIN-Inc | #Diablo4 | !youtube …",
      description:
        "Build: https://tinyurl.com/577yjt2e Twitch: https://www.twitch.tv/aceofspadeshots Mid Game: https://tinyurl.com/wmu9vd67 Leveling ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/Ytsy15xLtgc/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/Ytsy15xLtgc/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/Ytsy15xLtgc/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Goblin Inc.",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T07:56:26Z",
    },
  },
];

export const redditData = [
  {
    id: "t3_1fjaoao",
    parsedId: "1fjaoao",
    url: "https://www.reddit.com/r/MildlyBadDrivers/comments/1fjaoao/a_car_and_a_motorcycle_and_a_woman/",
    username: "Rave4life79",
    userId: "t2_vagqya9fv",
    title: "A car and a motorcycle and a woman",
    communityName: "r/MildlyBadDrivers",
    parsedCommunityName: "MildlyBadDrivers",
    body: "URL: https://v.redd.it/gdig2p25ofpd1\nThumbnail: https://external-preview.redd.it/bGFhamlydTRvZnBkMdYivT4SpoA73NvJpf-wku_UslFlqEbviWlL4rzpd3nE.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=cada6d1521cbd6095dc9fc76e2a991693cc9955e\nImages:\n\thttps://external-preview.redd.it/bGFhamlydTRvZnBkMdYivT4SpoA73NvJpf-wku_UslFlqEbviWlL4rzpd3nE.png?format=pjpg&amp;auto=webp&amp;s=1fb899aae5994b111d5e7d1fe7c2ac4d2a02ab9f\n",
    html: null,
    numberOfComments: 2053,
    flair: null,
    upVotes: 12616,
    upVoteRatio: 0.93,
    isVideo: true,
    isAd: false,
    over18: false,
    videoUrl: "https://v.redd.it/gdig2p25ofpd1/DASH_480.mp4?source=fallback",
    thumbnailUrl:
      "https://external-preview.redd.it/bGFhamlydTRvZnBkMdYivT4SpoA73NvJpf-wku_UslFlqEbviWlL4rzpd3nE.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=cada6d1521cbd6095dc9fc76e2a991693cc9955e",
    createdAt: "2024-09-17T20:58:20.000Z",
    scrapedAt: "2024-10-13T18:16:55.852Z",
    dataType: "post",
  },
  {
    id: "t1_lnmsi3x",
    parsedId: "lnmsi3x",
    url: "https://www.reddit.com/r/MildlyBadDrivers/comments/1fjaoao/a_car_and_a_motorcycle_and_a_woman/lnmsi3x/",
    postId: "t3_1fjaoao",
    parentId: "t3_1fjaoao",
    username: "AutoModerator",
    userId: "t2_6l4z3",
    category: "MildlyBadDrivers",
    communityName: "r/MildlyBadDrivers",
    body: "Sick of bad drivers? Want to support some movements that reduce car \ndependence? Support our friends at /r/Georgism and /r/yimby!\n\n[Georgism 101](https://www.youtube.com/watch?v=smi_iIoKybg)\n\n[YIMBY 101](https://youtu.be/0Flsg_mzG-M?si=tO9OqgRtp1j0AZoX)\n\n*I am a bot, and this action was performed automatically. Please [contact the moderators of this subreddit](/message/compose/?to=/r/MildlyBadDrivers) if you have any questions or concerns.*",
    createdAt: "2024-09-17T20:58:29.000Z",
    scrapedAt: "2024-10-13T18:16:55.880Z",
    upVotes: 1,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;Sick of bad drivers? Want to support some movements that reduce car \ndependence? Support our friends at &lt;a href="/r/Georgism"&gt;/r/Georgism&lt;/a&gt; and &lt;a href="/r/yimby"&gt;/r/yimby&lt;/a&gt;!&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://www.youtube.com/watch?v=smi_iIoKybg"&gt;Georgism 101&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://youtu.be/0Flsg_mzG-M?si=tO9OqgRtp1j0AZoX"&gt;YIMBY 101&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;em&gt;I am a bot, and this action was performed automatically. Please &lt;a href="/message/compose/?to=/r/MildlyBadDrivers"&gt;contact the moderators of this subreddit&lt;/a&gt; if you have any questions or concerns.&lt;/em&gt;&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lnn2g09",
    parsedId: "lnn2g09",
    url: "https://www.reddit.com/r/MildlyBadDrivers/comments/1fjaoao/a_car_and_a_motorcycle_and_a_woman/lnn2g09/",
    postId: "t3_1fjaoao",
    parentId: "t3_1fjaoao",
    username: "prominentdove",
    userId: "t2_1zzghh54",
    category: "MildlyBadDrivers",
    communityName: "r/MildlyBadDrivers",
    body: "I’m sorry but The Bee Gees song skipping is hilarious",
    createdAt: "2024-09-17T21:53:01.000Z",
    scrapedAt: "2024-10-13T18:16:55.880Z",
    upVotes: 630,
    numberOfreplies: 7,
    html: '&lt;div class="md"&gt;&lt;p&gt;I’m sorry but The Bee Gees song skipping is hilarious&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lnnvxey",
    parsedId: "lnnvxey",
    url: "https://www.reddit.com/r/MildlyBadDrivers/comments/1fjaoao/a_car_and_a_motorcycle_and_a_woman/lnnvxey/",
    postId: "t3_1fjaoao",
    parentId: "t1_lnn2g09",
    username: "SumthingBrewing",
    userId: "t2_9fi54zgn",
    category: "MildlyBadDrivers",
    communityName: "r/MildlyBadDrivers",
    body: "I swear, this song was used in something I saw recently like Breaking Bad or Ozark or something. Love the juxtaposition.\n\nAlthough “Staying Alive” would’ve been more apt.",
    createdAt: "2024-09-18T00:53:39.000Z",
    scrapedAt: "2024-10-13T18:16:55.880Z",
    upVotes: 95,
    numberOfreplies: 2,
    html: '&lt;div class="md"&gt;&lt;p&gt;I swear, this song was used in something I saw recently like Breaking Bad or Ozark or something. Love the juxtaposition.&lt;/p&gt;\n\n&lt;p&gt;Although “Staying Alive” would’ve been more apt.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lnodl9r",
    parsedId: "lnodl9r",
    url: "https://www.reddit.com/r/MildlyBadDrivers/comments/1fjaoao/a_car_and_a_motorcycle_and_a_woman/lnodl9r/",
    postId: "t3_1fjaoao",
    parentId: "t1_lnnvxey",
    username: "BetMyLastKrispyKreme",
    userId: "t2_un526hiyy",
    category: "MildlyBadDrivers",
    communityName: "r/MildlyBadDrivers",
    body: "But the driver *is* more than a woman. I think she’s the Grim Reaper in disguise.",
    createdAt: "2024-09-18T02:49:37.000Z",
    scrapedAt: "2024-10-13T18:16:55.880Z",
    upVotes: 57,
    numberOfreplies: 6,
    html: '&lt;div class="md"&gt;&lt;p&gt;But the driver &lt;em&gt;is&lt;/em&gt; more than a woman. I think she’s the Grim Reaper in disguise.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lnrrvef",
    parsedId: "lnrrvef",
    url: "https://www.reddit.com/r/MildlyBadDrivers/comments/1fjaoao/a_car_and_a_motorcycle_and_a_woman/lnrrvef/",
    postId: "t3_1fjaoao",
    parentId: "t1_lnodl9r",
    username: "Iokane_Powder_Diet",
    userId: "t2_16f21nlow1",
    category: "MildlyBadDrivers",
    communityName: "r/MildlyBadDrivers",
    body: "Lady Reaper was like, *oh darn, did I forget to clock out?*",
    createdAt: "2024-09-18T18:12:35.000Z",
    scrapedAt: "2024-10-13T18:16:55.880Z",
    upVotes: 23,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;Lady Reaper was like, &lt;em&gt;oh darn, did I forget to clock out?&lt;/em&gt;&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_1fo9ngc",
    parsedId: "1fo9ngc",
    url: "https://www.reddit.com/r/nextfuckinglevel/comments/1fo9ngc/dog_rushes_to_protect_girl_from_car_in_an/",
    username: "CreditorOP",
    userId: "t2_10fds47adc",
    title: "Dog Rushes to Protect Girl from Car in an Unexpected Move",
    communityName: "r/nextfuckinglevel",
    parsedCommunityName: "nextfuckinglevel",
    body: "URL: https://v.redd.it/2s1ny0ianqqd1\nThumbnail: https://external-preview.redd.it/cXhjNTExN2FucXFkMTnZmCDRoPWUDfL4K_H7epP3NI_RE3Yabaxtkar6JsdF.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=7f4241fbc3afb701b16053c28ce273b3aac323b2\nImages:\n\thttps://external-preview.redd.it/cXhjNTExN2FucXFkMTnZmCDRoPWUDfL4K_H7epP3NI_RE3Yabaxtkar6JsdF.png?format=pjpg&amp;auto=webp&amp;s=ec2f6740c68abd7e5374829946080328423b1697\n",
    html: null,
    numberOfComments: 657,
    flair: null,
    upVotes: 27650,
    upVoteRatio: 0.95,
    isVideo: true,
    isAd: false,
    over18: false,
    videoUrl: "https://v.redd.it/2s1ny0ianqqd1/DASH_1080.mp4?source=fallback",
    thumbnailUrl:
      "https://external-preview.redd.it/cXhjNTExN2FucXFkMTnZmCDRoPWUDfL4K_H7epP3NI_RE3Yabaxtkar6JsdF.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=7f4241fbc3afb701b16053c28ce273b3aac323b2",
    createdAt: "2024-09-24T10:57:04.000Z",
    scrapedAt: "2024-10-13T18:16:59.444Z",
    dataType: "post",
  },
  {
    id: "t1_loo6dpq",
    parsedId: "loo6dpq",
    url: "https://www.reddit.com/r/nextfuckinglevel/comments/1fo9ngc/dog_rushes_to_protect_girl_from_car_in_an/loo6dpq/",
    postId: "t3_1fo9ngc",
    parentId: "t3_1fo9ngc",
    username: "CreditorOP",
    userId: "t2_10fds47adc",
    category: "nextfuckinglevel",
    communityName: "r/nextfuckinglevel",
    body: "The dog's instinct was superb over here.",
    createdAt: "2024-09-24T10:58:31.000Z",
    scrapedAt: "2024-10-13T18:16:59.542Z",
    upVotes: 4961,
    numberOfreplies: 8,
    html: '&lt;div class="md"&gt;&lt;p&gt;The dog&amp;#39;s instinct was superb over here.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_loo78rd",
    parsedId: "loo78rd",
    url: "https://www.reddit.com/r/nextfuckinglevel/comments/1fo9ngc/dog_rushes_to_protect_girl_from_car_in_an/loo78rd/",
    postId: "t3_1fo9ngc",
    parentId: "t1_loo6dpq",
    username: "AlfaKaren",
    userId: "t2_avk0hnxvl",
    category: "nextfuckinglevel",
    communityName: "r/nextfuckinglevel",
    body: 'The other dog was like "not my problem" lol.',
    createdAt: "2024-09-24T11:06:17.000Z",
    scrapedAt: "2024-10-13T18:16:59.542Z",
    upVotes: 2278,
    numberOfreplies: 5,
    html: '&lt;div class="md"&gt;&lt;p&gt;The other dog was like &amp;quot;not my problem&amp;quot; lol.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_loo7iw8",
    parsedId: "loo7iw8",
    url: "https://www.reddit.com/r/nextfuckinglevel/comments/1fo9ngc/dog_rushes_to_protect_girl_from_car_in_an/loo7iw8/",
    postId: "t3_1fo9ngc",
    parentId: "t1_loo78rd",
    username: "CreditorOP",
    userId: "t2_10fds47adc",
    category: "nextfuckinglevel",
    communityName: "r/nextfuckinglevel",
    body: "The other dog looked back. maybe it was communicating to the hero dog to save the girl",
    createdAt: "2024-09-24T11:08:45.000Z",
    scrapedAt: "2024-10-13T18:16:59.542Z",
    upVotes: 1170,
    numberOfreplies: 7,
    html: '&lt;div class="md"&gt;&lt;p&gt;The other dog looked back. maybe it was communicating to the hero dog to save the girl&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
];
