export const rawData = [
  {
    kind: "youtube#searchResult",
    etag: "2JasxlistNqsMCdiiuDLJPErIcU",
    id: {
      kind: "youtube#video",
      videoId: "wxt77goIlXo",
    },
    snippet: {
      publishedAt: "2024-10-12T17:07:09Z",
      channelId: "UCq29tGmaqaKhChzbIHHNyqQ",
      title:
        "EASY ORANGE DRAWING, #easy #easydrawing #beginners #painting #artandcraft #art #drawingideas #diy",
      description:
        "EASY ORANGE DRAWING, #easy #easydrawing #beginners #painting #artandcraft #art #drawingideas #diy.",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/wxt77goIlXo/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/wxt77goIlXo/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/wxt77goIlXo/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "try it out",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T17:07:09Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "naEynmBsO1SYDASsn9fI4Mvi3pM",
    id: {
      kind: "youtube#video",
      videoId: "wWmAmGQdOu0",
    },
    snippet: {
      publishedAt: "2024-10-12T14:00:50Z",
      channelId: "UCw1lCaqwNbS34e235eVEyWQ",
      title: "Solved a Rubik&#39;s Cube color Orange",
      description: "",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/wWmAmGQdOu0/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/wWmAmGQdOu0/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/wWmAmGQdOu0/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "The Fighter",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T14:00:50Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "L7V3JMDIb8oLVMf_r0Tt-bu3pC4",
    id: {
      kind: "youtube#video",
      videoId: "oSfFfuuGxYI",
    },
    snippet: {
      publishedAt: "2024-10-12T13:42:13Z",
      channelId: "UCD8yoDPxz0id8OgGCRPiVIw",
      title: "ഇത്രയും ചെറിയ മരത്തിൽ orange ഇതുപോലെ കായിക്കുമോ? ടിപ്സ്.",
      description:
        "ഇത്രയും ചെറിയ മരത്തിൽ orange ഇതുപോലെ കായിക്കുമോ? ടിപ്സ്. Can an orange bear ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/oSfFfuuGxYI/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/oSfFfuuGxYI/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/oSfFfuuGxYI/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Rose Garden",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T13:42:13Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "t09cx-DC0QGHC8cvClLHFXcQj9c",
    id: {
      kind: "youtube#video",
      videoId: "wZGKufDhm70",
    },
    snippet: {
      publishedAt: "2024-10-12T13:03:16Z",
      channelId: "UCBfDfKIepnqC5pnWCAKikSg",
      title: "Orange ka real colour       #facts #factinhindi #factshorts",
      description: "Orange ka real colour #facts #factinhindi #factshorts.",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/wZGKufDhm70/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/wZGKufDhm70/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/wZGKufDhm70/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "TechMeraz ",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T13:03:16Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "2uT0VRrfryJ17oCsXBxWdBahIjM",
    id: {
      kind: "youtube#video",
      videoId: "qbSfTazMxkI",
    },
    snippet: {
      publishedAt: "2024-10-12T12:50:42Z",
      channelId: "UCBAVeOwX9GupXekfAp0J1oA",
      title: "If You Eat 1 Orange Every Day This Is What Happens To Your Body",
      description:
        "If You Eat 1 Orange Every Day This Is What Happens To Your Body #oranges #keto #ketodiet #weightloss #ketolifestyle ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/qbSfTazMxkI/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/qbSfTazMxkI/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/qbSfTazMxkI/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Diet Zone",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T12:50:42Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "DBcFlpICrzTRoONa4AywqzJTigA",
    id: {
      kind: "youtube#video",
      videoId: "2pVpngmH9bc",
    },
    snippet: {
      publishedAt: "2024-10-12T12:33:45Z",
      channelId: "UCWnnmlIKF975UuXGjc0TWmQ",
      title:
        "Get Glowing Skin with ORANGE PEEL! (Vitamin C Serum Hack) [2024]#shorts",
      description:
        "Unlock the secret to radiant, glowing skin with our latest DIY hack using orange peel! In this video, we'll show you how to create a ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/2pVpngmH9bc/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/2pVpngmH9bc/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/2pVpngmH9bc/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "The Ai Tara",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T12:33:45Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "2OrQT8DM99NY6jRowXCukRIGy98",
    id: {
      kind: "youtube#video",
      videoId: "zNK2da8K3ZM",
    },
    snippet: {
      publishedAt: "2024-10-12T12:01:16Z",
      channelId: "UC3S6nIDGJ5OtpC-mbvFA8Ew",
      title: "I Maxed out the Lavaloon Puppet",
      description:
        "New Halloween event in 2024. New hero equipment the Lavaloon puppet. Witch Golem, Barcher, Hog Wizard, Ice Minion and ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/zNK2da8K3ZM/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/zNK2da8K3ZM/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/zNK2da8K3ZM/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Orange Juice Gaming",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T12:01:16Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "vWtlNQok2IDchyq_9XMRzZtsMro",
    id: {
      kind: "youtube#video",
      videoId: "5u8UXyW7fDA",
    },
    snippet: {
      publishedAt: "2024-10-12T11:15:36Z",
      channelId: "UCm3cpXx3A7Lb3GgkcGYUV7g",
      title:
        "Orange peel home made face mask😍😍#trendingshorts #skincare #skincaretips #homemade #beauty",
      description:
        "Orange peel home made face mask    #trendingshorts #skincare #skincaretips #homemade #beauty.",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/5u8UXyW7fDA/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/5u8UXyW7fDA/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/5u8UXyW7fDA/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Anjum",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T11:15:36Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "1aHnDzaUL0rdTDpwCQBCERby67c",
    id: {
      kind: "youtube#video",
      videoId: "hFGhguimKHg",
    },
    snippet: {
      publishedAt: "2024-10-12T10:24:57Z",
      channelId: "UCCl62oBQfjUAjBg3AKYt7Ww",
      title: "how to draw an orange - Part 2 drawing fruits",
      description: "",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/hFGhguimKHg/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/hFGhguimKHg/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/hFGhguimKHg/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "colouring and drawing ",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T10:24:57Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "-yVeJBW1CAeAkjirMKrVeTo21vA",
    id: {
      kind: "youtube#video",
      videoId: "Ytsy15xLtgc",
    },
    snippet: {
      publishedAt: "2024-10-12T07:56:26Z",
      channelId: "UCYRJN1hoKPJ0GuQy7m5tWSw",
      title:
        "ORANGE QUILL |  SPIRITBORN RANK 1 PUSH | 150+ Beta Hours | GOBLIN-Inc | #Diablo4 | !youtube …",
      description:
        "Build: https://tinyurl.com/577yjt2e Twitch: https://www.twitch.tv/aceofspadeshots Mid Game: https://tinyurl.com/wmu9vd67 Leveling ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/Ytsy15xLtgc/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/Ytsy15xLtgc/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/Ytsy15xLtgc/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Goblin Inc.",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T07:56:26Z",
    },
  },
];

export const redditData = [
  {
    id: "t3_1ere0xh",
    parsedId: "1ere0xh",
    url: "https://www.reddit.com/r/apple/comments/1ere0xh/the_iphone_15_may_be_obsolete_faster_than_any/",
    username: "chrisdh79",
    userId: "t2_2uwit82z",
    title: "The iPhone 15 may be obsolete faster than any model in history",
    communityName: "r/apple",
    parsedCommunityName: "apple",
    body: "URL: https://9to5mac.com/2024/08/13/the-iphone-15-may-be-obsolete-faster-than-any-model-in-history/\nThumbnail: https://b.thumbs.redditmedia.com/N0scH6GPaqbHPTwWfMqFsJBBueTBegZt6QEsU2o1_UA.jpg\nImages:\n\thttps://external-preview.redd.it/zZGRZ4H-X5oSenBtCNr3zzIBATSLHw-8na2Y36My2dM.jpg?auto=webp&amp;s=a8c2d03f200bd379186e586698ae3930313c7c7d\n",
    html: null,
    numberOfComments: 923,
    flair: "iPhone",
    upVotes: 2728,
    upVoteRatio: 0.82,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl:
      "https://b.thumbs.redditmedia.com/N0scH6GPaqbHPTwWfMqFsJBBueTBegZt6QEsU2o1_UA.jpg",
    createdAt: "2024-08-13T17:35:48.000Z",
    scrapedAt: "2024-10-13T18:30:43.614Z",
    dataType: "post",
  },
  {
    id: "t1_lhyqv77",
    parsedId: "lhyqv77",
    url: "https://www.reddit.com/r/apple/comments/1ere0xh/the_iphone_15_may_be_obsolete_faster_than_any/lhyqv77/",
    postId: "t3_1ere0xh",
    parentId: "t3_1ere0xh",
    username: "pastalex42",
    userId: "t2_2jjzpinb",
    category: "apple",
    communityName: "r/apple",
    body: "I worked in a cell phone store for years around the iPhones 11-14. No one cares. They upgrade on whatever their schedule is, and no new features will change that. We tech interested folk are far and away the minority",
    createdAt: "2024-08-13T20:09:18.000Z",
    scrapedAt: "2024-10-13T18:30:43.714Z",
    upVotes: 2811,
    numberOfreplies: 12,
    html: '&lt;div class="md"&gt;&lt;p&gt;I worked in a cell phone store for years around the iPhones 11-14. No one cares. They upgrade on whatever their schedule is, and no new features will change that. We tech interested folk are far and away the minority&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_1fk2fbz",
    parsedId: "1fk2fbz",
    url: "https://www.reddit.com/r/technology/comments/1fk2fbz/apple_iphone_16_demand_is_so_weak_that_employees/",
    username: "lurker_bee",
    userId: "t2_c7n3w",
    title:
      "Apple iPhone 16 demand is so weak that employees can already buy it on discount",
    communityName: "r/technology",
    parsedCommunityName: "technology",
    body: "URL: https://qz.com/apple-iphone-16-pre-orders-sales-intelligence-ai-1851651638\nThumbnail: https://a.thumbs.redditmedia.com/OvZnOhPRNZrzLCjHSSF8qPB9bSj8hDC06M-_bsp6j00.jpg\nImages:\n\thttps://external-preview.redd.it/VKpzdsLyJbqv1idExkwMnOHpdgPdhDkvON0Tb3423OA.jpg?auto=webp&amp;s=42267fed176084c2022a957eab9a31c8e08c96cf\n",
    html: null,
    numberOfComments: 2931,
    flair: "Business",
    upVotes: 21843,
    upVoteRatio: 0.88,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl:
      "https://a.thumbs.redditmedia.com/OvZnOhPRNZrzLCjHSSF8qPB9bSj8hDC06M-_bsp6j00.jpg",
    createdAt: "2024-09-18T20:13:57.000Z",
    scrapedAt: "2024-10-13T18:30:43.815Z",
    dataType: "post",
  },
  {
    id: "t3_1fd55m7",
    parsedId: "1fd55m7",
    url: "https://www.reddit.com/r/iphone/comments/1fd55m7/60hz_display_on_iphone_16_is_criminal/",
    username: "srjchk",
    userId: "t2_f9056271",
    title: "60Hz Display on iPhone 16 is criminal",
    communityName: "r/iphone",
    parsedCommunityName: "iphone",
    body: "URL: https://i.redd.it/e7k6itrlnvnd1.jpeg\nThumbnail: https://a.thumbs.redditmedia.com/ovoljqu90FWt8Kp0UnHdpDXMrvaxOuGfTrlEweERib0.jpg\nImages:\n\thttps://preview.redd.it/e7k6itrlnvnd1.jpeg?auto=webp&amp;s=6cb81e9dab929e5c774bdafd923a2af0008972fa\n",
    html: null,
    numberOfComments: 1568,
    flair: "Discussion",
    upVotes: 9174,
    upVoteRatio: 0.92,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl:
      "https://a.thumbs.redditmedia.com/ovoljqu90FWt8Kp0UnHdpDXMrvaxOuGfTrlEweERib0.jpg",
    createdAt: "2024-09-10T00:35:19.000Z",
    scrapedAt: "2024-10-13T18:30:43.732Z",
    dataType: "post",
  },
  {
    id: "t1_lhzgak6",
    parsedId: "lhzgak6",
    url: "https://www.reddit.com/r/apple/comments/1ere0xh/the_iphone_15_may_be_obsolete_faster_than_any/lhzgak6/",
    postId: "t3_1ere0xh",
    parentId: "t1_lhyqv77",
    username: "Stingray88",
    userId: "t2_346h6",
    category: "apple",
    communityName: "r/apple",
    body: "I’m a tech enthusiast that spends way too much on a lot of shit, yet this is even true for me. I see new features on new phones and I don’t think to myself “I must buy that now!”, instead I think “I can’t wait to get that in the future when I’m ready for an upgrade!”\n\nAnd I’m not upgrading every 2 years either… I did 4 years with my 11 Pro, and I’m hoping my 15 Pro can go 5.",
    createdAt: "2024-08-13T22:47:34.000Z",
    scrapedAt: "2024-10-13T18:30:43.714Z",
    upVotes: 862,
    numberOfreplies: 6,
    html: '&lt;div class="md"&gt;&lt;p&gt;I’m a tech enthusiast that spends way too much on a lot of shit, yet this is even true for me. I see new features on new phones and I don’t think to myself “I must buy that now!”, instead I think “I can’t wait to get that in the future when I’m ready for an upgrade!”&lt;/p&gt;\n\n&lt;p&gt;And I’m not upgrading every 2 years either… I did 4 years with my 11 Pro, and I’m hoping my 15 Pro can go 5.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lnsttrm",
    parsedId: "lnsttrm",
    url: "https://www.reddit.com/r/technology/comments/1fk2fbz/apple_iphone_16_demand_is_so_weak_that_employees/lnsttrm/",
    postId: "t3_1fk2fbz",
    parentId: "t3_1fk2fbz",
    username: "barret88",
    userId: "t2_n5bab",
    category: "technology",
    communityName: "r/technology",
    body: "Didn’t employees always get a discount?",
    createdAt: "2024-09-18T21:30:53.000Z",
    scrapedAt: "2024-10-13T18:30:43.836Z",
    upVotes: 1559,
    numberOfreplies: 3,
    html: '&lt;div class="md"&gt;&lt;p&gt;Didn’t employees always get a discount?&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_li04vgh",
    parsedId: "li04vgh",
    url: "https://www.reddit.com/r/apple/comments/1ere0xh/the_iphone_15_may_be_obsolete_faster_than_any/li04vgh/",
    postId: "t3_1ere0xh",
    parentId: "t1_lhzgak6",
    username: "aBoyHasNoUzername",
    userId: "t2_fxv4wii",
    category: "apple",
    communityName: "r/apple",
    body: "Unless that feature is a feature like “Force Touch” that they take away to save costs",
    createdAt: "2024-08-14T01:20:04.000Z",
    scrapedAt: "2024-10-13T18:30:43.714Z",
    upVotes: 205,
    numberOfreplies: 4,
    html: '&lt;div class="md"&gt;&lt;p&gt;Unless that feature is a feature like “Force Touch” that they take away to save costs&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lntckfz",
    parsedId: "lntckfz",
    url: "https://www.reddit.com/r/technology/comments/1fk2fbz/apple_iphone_16_demand_is_so_weak_that_employees/lntckfz/",
    postId: "t3_1fk2fbz",
    parentId: "t1_lnsttrm",
    username: "daitenshe",
    userId: "t2_a5dh0",
    category: "technology",
    communityName: "r/technology",
    body: "Yes. Pretty much always same day as preorders for all except the most of insanely in demand products",
    createdAt: "2024-09-18T23:22:18.000Z",
    scrapedAt: "2024-10-13T18:30:43.836Z",
    upVotes: 626,
    numberOfreplies: 2,
    html: '&lt;div class="md"&gt;&lt;p&gt;Yes. Pretty much always same day as preorders for all except the most of insanely in demand products&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lnxa3ii",
    parsedId: "lnxa3ii",
    url: "https://www.reddit.com/r/technology/comments/1fk2fbz/apple_iphone_16_demand_is_so_weak_that_employees/lnxa3ii/",
    postId: "t3_1fk2fbz",
    parentId: "t1_lntckfz",
    username: "uneducated-caveman",
    userId: "t2_49t9m5j",
    category: "technology",
    communityName: "r/technology",
    body: "Employees personal discounts (one device per year) usually available day one or within a month. Friends and family discounts (10 devices per year) are based on demands. When iPhone 14 was released, FF\ndiscount wasn’t available until late November. \nThis time both personal and FF discounts are available now.",
    createdAt: "2024-09-19T17:06:49.000Z",
    scrapedAt: "2024-10-13T18:30:43.836Z",
    upVotes: 15,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;Employees personal discounts (one device per year) usually available day one or within a month. Friends and family discounts (10 devices per year) are based on demands. When iPhone 14 was released, FF\ndiscount wasn’t available until late November. \nThis time both personal and FF discounts are available now.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_li0qiub",
    parsedId: "li0qiub",
    url: "https://www.reddit.com/r/apple/comments/1ere0xh/the_iphone_15_may_be_obsolete_faster_than_any/li0qiub/",
    postId: "t3_1ere0xh",
    parentId: "t1_li04vgh",
    username: "pleasesteponmesinb",
    userId: "t2_105ydd",
    category: "apple",
    communityName: "r/apple",
    body: "Force Touch my beloved ..",
    createdAt: "2024-08-14T03:44:16.000Z",
    scrapedAt: "2024-10-13T18:30:43.715Z",
    upVotes: 69,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;Force Touch my beloved ..&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lnufn82",
    parsedId: "lnufn82",
    url: "https://www.reddit.com/r/technology/comments/1fk2fbz/apple_iphone_16_demand_is_so_weak_that_employees/lnufn82/",
    postId: "t3_1fk2fbz",
    parentId: "t1_lnsttrm",
    username: "WVVVWVWVVVVWVWVVVVVW",
    userId: "t2_jw36h",
    category: "technology",
    communityName: "r/technology",
    body: "Yes. This type of article comes out every year to clickbait people but each iPhone becomes the best selling ever simply because there's more people wanting a new phone. People will buy whatever is for sale as their upgrade.",
    createdAt: "2024-09-19T03:38:23.000Z",
    scrapedAt: "2024-10-13T18:30:43.836Z",
    upVotes: 309,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;Yes. This type of article comes out every year to clickbait people but each iPhone becomes the best selling ever simply because there&amp;#39;s more people wanting a new phone. People will buy whatever is for sale as their upgrade.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_li0xyj0",
    parsedId: "li0xyj0",
    url: "https://www.reddit.com/r/apple/comments/1ere0xh/the_iphone_15_may_be_obsolete_faster_than_any/li0xyj0/",
    postId: "t3_1ere0xh",
    parentId: "t1_li0qiub",
    username: "Stefanoverse",
    userId: "t2_5vpm92r5",
    category: "apple",
    communityName: "r/apple",
    body: "My thumb try’s to use it everyday when I’m typing. Such BS that they got rid of that.",
    createdAt: "2024-08-14T04:44:09.000Z",
    scrapedAt: "2024-10-13T18:30:43.715Z",
    upVotes: 39,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;My thumb try’s to use it everyday when I’m typing. Such BS that they got rid of that.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lmdhcv8",
    parsedId: "lmdhcv8",
    url: "https://www.reddit.com/r/iphone/comments/1fd55m7/60hz_display_on_iphone_16_is_criminal/lmdhcv8/",
    postId: "t3_1fd55m7",
    parentId: "t3_1fd55m7",
    username: "jbayne2",
    userId: "t2_452zi",
    category: "iphone",
    communityName: "r/iphone",
    body: "I’ve been a pro user since they came out with that option but I would switch to the regular plus immediately if it had 120hz and always on.",
    createdAt: "2024-09-10T01:44:50.000Z",
    scrapedAt: "2024-10-13T18:30:43.924Z",
    upVotes: 3140,
    numberOfreplies: 10,
    html: '&lt;div class="md"&gt;&lt;p&gt;I’ve been a pro user since they came out with that option but I would switch to the regular plus immediately if it had 120hz and always on.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lnsk9kh",
    parsedId: "lnsk9kh",
    url: "https://www.reddit.com/r/technology/comments/1fk2fbz/apple_iphone_16_demand_is_so_weak_that_employees/lnsk9kh/",
    postId: "t3_1fk2fbz",
    parentId: "t3_1fk2fbz",
    username: "tKNemesis",
    userId: "t2_7hemh",
    category: "technology",
    communityName: "r/technology",
    body: "I’m only upgrading from my 13 Pro because my carrier is still valuing my trade in as $1000. Next year I’m sure its value would be substantially lower so I took advantage.\n\nEdit: ATT is my carrier. If you go to Costco and do it you may get a Costco cash card too.",
    createdAt: "2024-09-18T20:40:05.000Z",
    scrapedAt: "2024-10-13T18:30:43.836Z",
    upVotes: 3069,
    numberOfreplies: 8,
    html: '&lt;div class="md"&gt;&lt;p&gt;I’m only upgrading from my 13 Pro because my carrier is still valuing my trade in as $1000. Next year I’m sure its value would be substantially lower so I took advantage.&lt;/p&gt;\n\n&lt;p&gt;Edit: ATT is my carrier. If you go to Costco and do it you may get a Costco cash card too.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lmdnxqw",
    parsedId: "lmdnxqw",
    url: "https://www.reddit.com/r/iphone/comments/1fd55m7/60hz_display_on_iphone_16_is_criminal/lmdnxqw/",
    postId: "t3_1fd55m7",
    parentId: "t1_lmdhcv8",
    username: "neatgeek83",
    userId: "t2_lmtx1",
    category: "iphone",
    communityName: "r/iphone",
    body: "That’s literally why. They’ll gladly take your extra $300",
    createdAt: "2024-09-10T02:26:28.000Z",
    scrapedAt: "2024-10-13T18:30:43.924Z",
    upVotes: 2089,
    numberOfreplies: 3,
    html: '&lt;div class="md"&gt;&lt;p&gt;That’s literally why. They’ll gladly take your extra $300&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lme4k2c",
    parsedId: "lme4k2c",
    url: "https://www.reddit.com/r/iphone/comments/1fd55m7/60hz_display_on_iphone_16_is_criminal/lme4k2c/",
    postId: "t3_1fd55m7",
    parentId: "t1_lmdnxqw",
    username: "CR7KRUL",
    userId: "t2_tmkvdi7v",
    category: "iphone",
    communityName: "r/iphone",
    body: "$200",
    createdAt: "2024-09-10T04:30:37.000Z",
    scrapedAt: "2024-10-13T18:30:43.924Z",
    upVotes: 330,
    numberOfreplies: 2,
    html: '&lt;div class="md"&gt;&lt;p&gt;$200&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lme55cb",
    parsedId: "lme55cb",
    url: "https://www.reddit.com/r/iphone/comments/1fd55m7/60hz_display_on_iphone_16_is_criminal/lme55cb/",
    postId: "t3_1fd55m7",
    parentId: "t1_lme4k2c",
    username: "CigarLover",
    userId: "t2_5lz5u",
    category: "iphone",
    communityName: "r/iphone",
    body: "About 170 actually. \n\n1029 vs 1199\n\nWhich makes it a no brainer for people that buy it out right.\n\nThat’s a 256gb Plus vs a 256gb Pro Max",
    createdAt: "2024-09-10T04:35:48.000Z",
    scrapedAt: "2024-10-13T18:30:43.924Z",
    upVotes: 251,
    numberOfreplies: 2,
    html: '&lt;div class="md"&gt;&lt;p&gt;About 170 actually. &lt;/p&gt;\n\n&lt;p&gt;1029 vs 1199&lt;/p&gt;\n\n&lt;p&gt;Which makes it a no brainer for people that buy it out right.&lt;/p&gt;\n\n&lt;p&gt;That’s a 256gb Plus vs a 256gb Pro Max&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lmfg53u",
    parsedId: "lmfg53u",
    url: "https://www.reddit.com/r/iphone/comments/1fd55m7/60hz_display_on_iphone_16_is_criminal/lmfg53u/",
    postId: "t3_1fd55m7",
    parentId: "t1_lme55cb",
    username: "PoundBig1488",
    userId: "t2_17nsbvtrmo",
    category: "iphone",
    communityName: "r/iphone",
    body: "Damn, it's about $1700 for the pro max 256GB in Sweden.",
    createdAt: "2024-09-10T12:35:18.000Z",
    scrapedAt: "2024-10-13T18:30:43.924Z",
    upVotes: 101,
    numberOfreplies: 3,
    html: '&lt;div class="md"&gt;&lt;p&gt;Damn, it&amp;#39;s about $1700 for the pro max 256GB in Sweden.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_197w148",
    parsedId: "197w148",
    url: "https://www.reddit.com/r/applesucks/comments/197w148/how_is_it_that_iphones_are_considered_exclusive/",
    username: "ToastzPogggg",
    userId: "t2_9fgeqflm",
    title: "How is it that iPhones are considered exclusive and status items!?",
    communityName: "r/applesucks",
    parsedCommunityName: "applesucks",
    body: "I don't understand how iPhones are considered exclusive... It doesn't make sense. You see so many more iPhones than Androids in my area, yet they still somehow remain status items. Are people actually that blind. The iPhone is more common, you see them everywhere. You'd think the androids would become exclusive then. Plus the folding samsungs would also be more \"exclusive\" since they have a much higher pricetag than the iPhones maxes as well as being more rare. I don't understand the appeal.... I don't hate iPhone users its just wild to me. I mean your paying more for less I guess you could say\n\nDoes anyone understand why people think this way?",
    html: '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;I don&amp;#39;t understand how iPhones are considered exclusive... It doesn&amp;#39;t make sense. You see so many more iPhones than Androids in my area, yet they still somehow remain status items. Are people actually that blind. The iPhone is more common, you see them everywhere. You&amp;#39;d think the androids would become exclusive then. Plus the folding samsungs would also be more &amp;quot;exclusive&amp;quot; since they have a much higher pricetag than the iPhones maxes as well as being more rare. I don&amp;#39;t understand the appeal.... I don&amp;#39;t hate iPhone users its just wild to me. I mean your paying more for less I guess you could say&lt;/p&gt;\n\n&lt;p&gt;Does anyone understand why people think this way?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
    numberOfComments: 150,
    flair: null,
    upVotes: 31,
    upVoteRatio: 0.8,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl: "self",
    createdAt: "2024-01-16T06:19:36.000Z",
    scrapedAt: "2024-10-13T18:30:46.215Z",
    dataType: "post",
  },
  {
    id: "t1_ki3e7zp",
    parsedId: "ki3e7zp",
    url: "https://www.reddit.com/r/applesucks/comments/197w148/how_is_it_that_iphones_are_considered_exclusive/ki3e7zp/",
    postId: "t3_197w148",
    parentId: "t3_197w148",
    username: "Psilent_P_",
    userId: "t2_thfso9hg",
    category: "applesucks",
    communityName: "r/applesucks",
    body: "Because that's what Apple had to evolve into. there hasn't been a software/hardware reason to buy an iPhone for years. There is an android equivalent for everything now, and IMO many better options, often cheaper. It's why they don't/can't compete globally... If they lowered the price of entry, it would destroy the brand and appeal. \n\nIt's not that people belittle android users because they have androids... It's that the type of people that buy iPhones are the type of people that belittle others... Generally speaking of course, I know there are iPhone users that are perfectly nice 🙂",
    createdAt: "2024-01-16T07:14:33.000Z",
    scrapedAt: "2024-10-13T18:30:46.309Z",
    upVotes: 17,
    numberOfreplies: 3,
    html: '&lt;div class="md"&gt;&lt;p&gt;Because that&amp;#39;s what Apple had to evolve into. there hasn&amp;#39;t been a software/hardware reason to buy an iPhone for years. There is an android equivalent for everything now, and IMO many better options, often cheaper. It&amp;#39;s why they don&amp;#39;t/can&amp;#39;t compete globally... If they lowered the price of entry, it would destroy the brand and appeal. &lt;/p&gt;\n\n&lt;p&gt;It&amp;#39;s not that people belittle android users because they have androids... It&amp;#39;s that the type of people that buy iPhones are the type of people that belittle others... Generally speaking of course, I know there are iPhone users that are perfectly nice 🙂&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_ki3eo2u",
    parsedId: "ki3eo2u",
    url: "https://www.reddit.com/r/applesucks/comments/197w148/how_is_it_that_iphones_are_considered_exclusive/ki3eo2u/",
    postId: "t3_197w148",
    parentId: "t1_ki3e7zp",
    username: "ToastzPogggg",
    userId: "t2_9fgeqflm",
    category: "applesucks",
    communityName: "r/applesucks",
    body: "I, too know nice iPhone users, it's just a shame that people are that way sometimes though",
    createdAt: "2024-01-16T07:19:25.000Z",
    scrapedAt: "2024-10-13T18:30:46.309Z",
    upVotes: 1,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;I, too know nice iPhone users, it&amp;#39;s just a shame that people are that way sometimes though&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_ki4lqco",
    parsedId: "ki4lqco",
    url: "https://www.reddit.com/r/applesucks/comments/197w148/how_is_it_that_iphones_are_considered_exclusive/ki4lqco/",
    postId: "t3_197w148",
    parentId: "t1_ki3eo2u",
    username: "luzer_kidd",
    userId: "t2_3gy71kkh",
    category: "applesucks",
    communityName: "r/applesucks",
    body: "Apple has been ripping their customers off for decades, but their users are like a cult and support them. I know this post is about iphones, but do a Google search with how many times apple has changed cpu brands who all have different cpu architectures which turns into no backwards compatibility and a cutoff of support. It's a horrible way to treat your customers, but for some reason people continue to take their side.\n\nThis doesn't mean windows or linux distros are perfect, but at the very least there are many options when purchasing hardware that has a better price to performance ratio.",
    createdAt: "2024-01-16T14:35:24.000Z",
    scrapedAt: "2024-10-13T18:30:46.309Z",
    upVotes: 6,
    numberOfreplies: 2,
    html: '&lt;div class="md"&gt;&lt;p&gt;Apple has been ripping their customers off for decades, but their users are like a cult and support them. I know this post is about iphones, but do a Google search with how many times apple has changed cpu brands who all have different cpu architectures which turns into no backwards compatibility and a cutoff of support. It&amp;#39;s a horrible way to treat your customers, but for some reason people continue to take their side.&lt;/p&gt;\n\n&lt;p&gt;This doesn&amp;#39;t mean windows or linux distros are perfect, but at the very least there are many options when purchasing hardware that has a better price to performance ratio.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_ki6k93p",
    parsedId: "ki6k93p",
    url: "https://www.reddit.com/r/applesucks/comments/197w148/how_is_it_that_iphones_are_considered_exclusive/ki6k93p/",
    postId: "t3_197w148",
    parentId: "t1_ki4lqco",
    username: "ToastzPogggg",
    userId: "t2_9fgeqflm",
    category: "applesucks",
    communityName: "r/applesucks",
    body: 'It definitively doesn\'t help the matter on iPhones being "better"',
    createdAt: "2024-01-16T21:09:46.000Z",
    scrapedAt: "2024-10-13T18:30:46.309Z",
    upVotes: 2,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;It definitively doesn&amp;#39;t help the matter on iPhones being &amp;quot;better&amp;quot;&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_kiajp9k",
    parsedId: "kiajp9k",
    url: "https://www.reddit.com/r/applesucks/comments/197w148/how_is_it_that_iphones_are_considered_exclusive/kiajp9k/",
    postId: "t3_197w148",
    parentId: "t1_ki6k93p",
    username: "luzer_kidd",
    userId: "t2_3gy71kkh",
    category: "applesucks",
    communityName: "r/applesucks",
    body: "As much as I hate Apple, it's still a good thing for them to be around for competition. If we just want to talk about phones. Windows blew it with horrible app support. So if apple wasn't around it would only be android and it's not a good idea to only have 1 company/os",
    createdAt: "2024-01-17T15:47:55.000Z",
    scrapedAt: "2024-10-13T18:30:46.309Z",
    upVotes: 3,
    numberOfreplies: 2,
    html: '&lt;div class="md"&gt;&lt;p&gt;As much as I hate Apple, it&amp;#39;s still a good thing for them to be around for competition. If we just want to talk about phones. Windows blew it with horrible app support. So if apple wasn&amp;#39;t around it would only be android and it&amp;#39;s not a good idea to only have 1 company/os&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_1fwi7bg",
    parsedId: "1fwi7bg",
    url: "https://www.reddit.com/r/CreditCardsIndia/comments/1fwi7bg/iphone_16_256_gb_27000/",
    username: "Wild_Muscle3506",
    userId: "t2_d3y5q3nd",
    title: "iPhone 16 256 GB  - 27,000",
    communityName: "r/CreditCardsIndia",
    parsedCommunityName: "CreditCardsIndia",
    body: "URL: https://i.redd.it/1valh6t16vsd1.jpeg\nThumbnail: https://b.thumbs.redditmedia.com/-T84l3Rni7MHGQgl5mQ_xgYxVzhJTlC5sfSfzMK7DDk.jpg\nImages:\n\thttps://preview.redd.it/1valh6t16vsd1.jpeg?auto=webp&amp;s=2d46f163caf7fcc98066fc251afe16756c62cc46\n",
    html: null,
    numberOfComments: 220,
    flair: "General Discussion/Conversation",
    upVotes: 2158,
    upVoteRatio: 0.99,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl:
      "https://b.thumbs.redditmedia.com/-T84l3Rni7MHGQgl5mQ_xgYxVzhJTlC5sfSfzMK7DDk.jpg",
    createdAt: "2024-10-05T04:17:35.000Z",
    scrapedAt: "2024-10-13T18:30:48.117Z",
    dataType: "post",
  },
  {
    id: "t1_lqesyzf",
    parsedId: "lqesyzf",
    url: "https://www.reddit.com/r/CreditCardsIndia/comments/1fwi7bg/iphone_16_256_gb_27000/lqesyzf/",
    postId: "t3_1fwi7bg",
    parentId: "t3_1fwi7bg",
    username: "ifthingscouldsee",
    userId: "t2_31rijto9",
    category: "CreditCardsIndia",
    communityName: "r/CreditCardsIndia",
    body: "Congratulations! Approx how much spends did you do to accumulate 62930 Points?",
    createdAt: "2024-10-05T04:23:31.000Z",
    scrapedAt: "2024-10-13T18:30:48.204Z",
    upVotes: 233,
    numberOfreplies: 3,
    html: '&lt;div class="md"&gt;&lt;p&gt;Congratulations! Approx how much spends did you do to accumulate 62930 Points?&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lqeuo3b",
    parsedId: "lqeuo3b",
    url: "https://www.reddit.com/r/CreditCardsIndia/comments/1fwi7bg/iphone_16_256_gb_27000/lqeuo3b/",
    postId: "t3_1fwi7bg",
    parentId: "t1_lqesyzf",
    username: "thelostknight99",
    userId: "t2_4jp70y",
    category: "CreditCardsIndia",
    communityName: "r/CreditCardsIndia",
    body: "Points should be more right? 62930 is the INR amount. Does infinia give 1:1 conversion on INR?",
    createdAt: "2024-10-05T04:38:55.000Z",
    scrapedAt: "2024-10-13T18:30:48.204Z",
    upVotes: 107,
    numberOfreplies: 4,
    html: '&lt;div class="md"&gt;&lt;p&gt;Points should be more right? 62930 is the INR amount. Does infinia give 1:1 conversion on INR?&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lqevfvl",
    parsedId: "lqevfvl",
    url: "https://www.reddit.com/r/CreditCardsIndia/comments/1fwi7bg/iphone_16_256_gb_27000/lqevfvl/",
    postId: "t3_1fwi7bg",
    parentId: "t1_lqeuo3b",
    username: "dumbass_random",
    userId: "t2_wdeer",
    category: "CreditCardsIndia",
    communityName: "r/CreditCardsIndia",
    body: "Infinia does not give 1:1 on conversion. It allows you to spend 1:1 on flights hotels and apple products (usually iphone on launch is not listed on the portal). _How OP got it is a mystery_\n\n\nEdit:\nApparently it is visible on smartbuy portal. Just not under all things apple.  HDFC being HDFC",
    createdAt: "2024-10-05T04:46:03.000Z",
    scrapedAt: "2024-10-13T18:30:48.204Z",
    upVotes: 132,
    numberOfreplies: 2,
    html: '&lt;div class="md"&gt;&lt;p&gt;Infinia does not give 1:1 on conversion. It allows you to spend 1:1 on flights hotels and apple products (usually iphone on launch is not listed on the portal). &lt;em&gt;How OP got it is a mystery&lt;/em&gt;&lt;/p&gt;\n\n&lt;p&gt;Edit:\nApparently it is visible on smartbuy portal. Just not under all things apple.  HDFC being HDFC&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lqevl88",
    parsedId: "lqevl88",
    url: "https://www.reddit.com/r/CreditCardsIndia/comments/1fwi7bg/iphone_16_256_gb_27000/lqevl88/",
    postId: "t3_1fwi7bg",
    parentId: "t1_lqevfvl",
    username: "thelostknight99",
    userId: "t2_4jp70y",
    category: "CreditCardsIndia",
    communityName: "r/CreditCardsIndia",
    body: "Maybe they paid by using more points? It's not mentioned anywhere on the screenshot how many points were used to pay the 62k amount.",
    createdAt: "2024-10-05T04:47:27.000Z",
    scrapedAt: "2024-10-13T18:30:48.204Z",
    upVotes: 34,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;Maybe they paid by using more points? It&amp;#39;s not mentioned anywhere on the screenshot how many points were used to pay the 62k amount.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lqevsb8",
    parsedId: "lqevsb8",
    url: "https://www.reddit.com/r/CreditCardsIndia/comments/1fwi7bg/iphone_16_256_gb_27000/lqevsb8/",
    postId: "t3_1fwi7bg",
    parentId: "t1_lqevl88",
    username: "dumbass_random",
    userId: "t2_wdeer",
    category: "CreditCardsIndia",
    communityName: "r/CreditCardsIndia",
    body: "Maybe but where exactly did OP burn those points.\nAFAIK, reward points can be burnt on smartbuy portal only. And iphone 16 is not listed there",
    createdAt: "2024-10-05T04:49:19.000Z",
    scrapedAt: "2024-10-13T18:30:48.204Z",
    upVotes: 6,
    numberOfreplies: 3,
    html: '&lt;div class="md"&gt;&lt;p&gt;Maybe but where exactly did OP burn those points.\nAFAIK, reward points can be burnt on smartbuy portal only. And iphone 16 is not listed there&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_1er6h8q",
    parsedId: "1er6h8q",
    url: "https://www.reddit.com/r/iphone/comments/1er6h8q/iphone_16_leaked_pics/",
    username: "kaxeno5",
    userId: "t2_14x7uw3496",
    title: "iPhone 16 Leaked Pics",
    communityName: "r/iphone",
    parsedCommunityName: "iphone",
    body: "URL: https://www.reddit.com/gallery/1er6h8q\nThumbnail: https://b.thumbs.redditmedia.com/fO_24lT6n-K_NjPd9IF7jPLjFYgJ7m69sC4GPVTW5sQ.jpg\n",
    html: null,
    numberOfComments: 1018,
    flair: "News/Rumour",
    upVotes: 4215,
    upVoteRatio: 0.89,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl:
      "https://b.thumbs.redditmedia.com/fO_24lT6n-K_NjPd9IF7jPLjFYgJ7m69sC4GPVTW5sQ.jpg",
    createdAt: "2024-08-13T12:22:26.000Z",
    scrapedAt: "2024-10-13T18:30:48.616Z",
    dataType: "post",
  },
  {
    id: "t1_lhwm7on",
    parsedId: "lhwm7on",
    url: "https://www.reddit.com/r/iphone/comments/1er6h8q/iphone_16_leaked_pics/lhwm7on/",
    postId: "t3_1er6h8q",
    parentId: "t3_1er6h8q",
    username: "Legal-Place3873",
    userId: "t2_r29ka6j34",
    category: "iphone",
    communityName: "r/iphone",
    body: "Looks like an updated iPhone X",
    createdAt: "2024-08-13T13:18:51.000Z",
    scrapedAt: "2024-10-13T18:30:48.708Z",
    upVotes: 1874,
    numberOfreplies: 6,
    html: '&lt;div class="md"&gt;&lt;p&gt;Looks like an updated iPhone X&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lhx009f",
    parsedId: "lhx009f",
    url: "https://www.reddit.com/r/iphone/comments/1er6h8q/iphone_16_leaked_pics/lhx009f/",
    postId: "t3_1er6h8q",
    parentId: "t1_lhwm7on",
    username: "RazorThin55",
    userId: "t2_3l5tgj1m",
    category: "iphone",
    communityName: "r/iphone",
    body: "As a current XS user wanting to upgrade to the 16 I see this as a win",
    createdAt: "2024-08-13T14:38:58.000Z",
    scrapedAt: "2024-10-13T18:30:48.708Z",
    upVotes: 646,
    numberOfreplies: 4,
    html: '&lt;div class="md"&gt;&lt;p&gt;As a current XS user wanting to upgrade to the 16 I see this as a win&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lhxklzt",
    parsedId: "lhxklzt",
    url: "https://www.reddit.com/r/iphone/comments/1er6h8q/iphone_16_leaked_pics/lhxklzt/",
    postId: "t3_1er6h8q",
    parentId: "t1_lhx009f",
    username: "One_pop_each",
    userId: "t2_nj3y3",
    category: "iphone",
    communityName: "r/iphone",
    body: "I miss my X. I have a 12 Pro and want something smaller. I don’t need a better camera. I’m not out taking time-lapses of the Milky Way. I take candid photos of my daughter and stock number shit from work.",
    createdAt: "2024-08-13T16:27:08.000Z",
    scrapedAt: "2024-10-13T18:30:48.708Z",
    upVotes: 203,
    numberOfreplies: 4,
    html: '&lt;div class="md"&gt;&lt;p&gt;I miss my X. I have a 12 Pro and want something smaller. I don’t need a better camera. I’m not out taking time-lapses of the Milky Way. I take candid photos of my daughter and stock number shit from work.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lhxuyi8",
    parsedId: "lhxuyi8",
    url: "https://www.reddit.com/r/iphone/comments/1er6h8q/iphone_16_leaked_pics/lhxuyi8/",
    postId: "t3_1er6h8q",
    parentId: "t1_lhxklzt",
    username: "OkDragonfruit9026",
    userId: "t2_d4pgg1miy",
    category: "iphone",
    communityName: "r/iphone",
    body: "Im out taking timelapses of the Milky Way as we speak (for real) and I’ve got a 13 mini.",
    createdAt: "2024-08-13T17:21:25.000Z",
    scrapedAt: "2024-10-13T18:30:48.708Z",
    upVotes: 85,
    numberOfreplies: 6,
    html: '&lt;div class="md"&gt;&lt;p&gt;Im out taking timelapses of the Milky Way as we speak (for real) and I’ve got a 13 mini.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_li04d14",
    parsedId: "li04d14",
    url: "https://www.reddit.com/r/iphone/comments/1er6h8q/iphone_16_leaked_pics/li04d14/",
    postId: "t3_1er6h8q",
    parentId: "t1_lhxuyi8",
    username: "Mmmariokart",
    userId: "t2_wvn9oin",
    category: "iphone",
    communityName: "r/iphone",
    body: "Show us the results when done. There's a pic upload button here",
    createdAt: "2024-08-14T01:16:51.000Z",
    scrapedAt: "2024-10-13T18:30:48.708Z",
    upVotes: 40,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;Show us the results when done. There&amp;#39;s a pic upload button here&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_1fc5o8w",
    parsedId: "1fc5o8w",
    url: "https://www.reddit.com/r/apple/comments/1fc5o8w/apple_set_to_unveil_iphone_16_on_monday_heres/",
    username: "A-Dog22",
    userId: "t2_p50ra",
    title: "Apple set to unveil iPhone 16 on Monday. Here's what to expect.",
    communityName: "r/apple",
    parsedCommunityName: "apple",
    body: "URL: https://www.cbsnews.com/news/apple-iphone-16-what-to-expect/\nThumbnail: https://b.thumbs.redditmedia.com/3cTElUw8fJcfnSviEOpB3QxVhowxrtUWEMaFjiobU3I.jpg\nImages:\n\thttps://external-preview.redd.it/TpHxaBvRYIWsIYlYqiOQWoDWmYRJ45ORMJuqPQY29OQ.jpg?auto=webp&amp;s=1f5cca00ccf181e32b0daa2bfce2774df8e67f23\n",
    html: null,
    numberOfComments: 1117,
    flair: "iPhone",
    upVotes: 3412,
    upVoteRatio: 0.89,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl:
      "https://b.thumbs.redditmedia.com/3cTElUw8fJcfnSviEOpB3QxVhowxrtUWEMaFjiobU3I.jpg",
    createdAt: "2024-09-08T19:13:23.000Z",
    scrapedAt: "2024-10-13T18:30:50.309Z",
    dataType: "post",
  },
  {
    id: "t1_lm60f46",
    parsedId: "lm60f46",
    url: "https://www.reddit.com/r/apple/comments/1fc5o8w/apple_set_to_unveil_iphone_16_on_monday_heres/lm60f46/",
    postId: "t3_1fc5o8w",
    parentId: "t3_1fc5o8w",
    username: "Orgasmitchh",
    userId: "t2_etv9t",
    category: "apple",
    communityName: "r/apple",
    body: "Im gonna be upgrading just because I want to break up with all of my lightning cables",
    createdAt: "2024-09-08T19:50:09.000Z",
    scrapedAt: "2024-10-13T18:30:50.402Z",
    upVotes: 2556,
    numberOfreplies: 7,
    html: '&lt;div class="md"&gt;&lt;p&gt;Im gonna be upgrading just because I want to break up with all of my lightning cables&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lm66p4i",
    parsedId: "lm66p4i",
    url: "https://www.reddit.com/r/apple/comments/1fc5o8w/apple_set_to_unveil_iphone_16_on_monday_heres/lm66p4i/",
    postId: "t3_1fc5o8w",
    parentId: "t1_lm60f46",
    username: "Cheeetooos",
    userId: "t2_wttci",
    category: "apple",
    communityName: "r/apple",
    body: "I have a 12 and my wife got the 15 pro last year. I’m tempted to upgrade and honestly this is a big part of why. The other factor is the camera which doesn’t hold a candle to her 15 pro. My 12 is still kicking though. Not sure if I’ll pull the trigger or not. I tend to buy at launch or just wait an entire additional year so we will see what tomorrow brings.",
    createdAt: "2024-09-08T20:22:07.000Z",
    scrapedAt: "2024-10-13T18:30:50.402Z",
    upVotes: 530,
    numberOfreplies: 7,
    html: '&lt;div class="md"&gt;&lt;p&gt;I have a 12 and my wife got the 15 pro last year. I’m tempted to upgrade and honestly this is a big part of why. The other factor is the camera which doesn’t hold a candle to her 15 pro. My 12 is still kicking though. Not sure if I’ll pull the trigger or not. I tend to buy at launch or just wait an entire additional year so we will see what tomorrow brings.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lm6dd77",
    parsedId: "lm6dd77",
    url: "https://www.reddit.com/r/apple/comments/1fc5o8w/apple_set_to_unveil_iphone_16_on_monday_heres/lm6dd77/",
    postId: "t3_1fc5o8w",
    parentId: "t1_lm66p4i",
    username: "whatever604",
    userId: "t2_idkrv",
    category: "apple",
    communityName: "r/apple",
    body: "same situation, I’m just gonna upgrade and then “upgrade” my dad to my old 12 pro",
    createdAt: "2024-09-08T20:57:01.000Z",
    scrapedAt: "2024-10-13T18:30:50.402Z",
    upVotes: 154,
    numberOfreplies: 3,
    html: '&lt;div class="md"&gt;&lt;p&gt;same situation, I’m just gonna upgrade and then “upgrade” my dad to my old 12 pro&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_18xm33x",
    parsedId: "18xm33x",
    url: "https://www.reddit.com/r/samsung/comments/18xm33x/just_switched_to_iphone_and_regret_it/",
    username: "Xtoron2",
    userId: "t2_92l1gpx2",
    title: "Just switched to Iphone and regret it",
    communityName: "r/samsung",
    parsedCommunityName: "samsung",
    body: "My note 20u's battery is dying after heavy use for 3+ years so i decided to get an iphone 15 pro max for a change. It's my first time on ios but i'm not a stranger to it because we have an ipad. \n\nHere are my pros:\n\n&gt; battery is superior(a bit better compared to my wife's s23u)\n&gt; phone speaker is top notch\n&gt; camera operation is faster and transition between lenses is more fluid\n&gt; camera quality when on social media apps are much better(i dont use it but it's better)\n&gt; always on display is much better\n\nCons:\n\n&gt; no universal back gesture (Can't use one hand properly because of this. Always have to reach for the top left to go back. Funny thing is it's not even consistent, sometimes it's on the lower left on some apps\n&gt; placement of the action button makes it useless. It's in a hard to reach spot when using one hand so it's faster to just open the phone\n&gt; Home screen is a mess. You can grouo them into folders but still a mess and harder to organize vs Oneui\n&gt; Several times i've had issues receiving a text. I tested it by sending a text message from s23u and i would receive the message after maybe 5 mins. When i reply back, the s23u would receive it right away\n&gt; notification center is a mess compared to one ui's or any androids\n&gt; always have to go to Settings app to change settings from some apps\n&gt; in my use case I think fingerprint is more convenient than face id. When working and want to check something from my phone lying on the table, I hate that i have to bring it up and face id vs just using fingerprint\n&gt; s23u feels snappier. Yes it does. Faster swipes and the screen refresh rate is more consistently at 120hz than my 15pm\n\nI just think you can do things faster on one ui and it's easier to use one handed even considering the latest oneui update where the drop down menu pushed some things higher. \n\nI'm debating on returning my phone and wait for the s24u. Or maybe im just too used to oneui and i need to spend more time on ios.",
    html: '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;My note 20u&amp;#39;s battery is dying after heavy use for 3+ years so i decided to get an iphone 15 pro max for a change. It&amp;#39;s my first time on ios but i&amp;#39;m not a stranger to it because we have an ipad. &lt;/p&gt;\n\n&lt;p&gt;Here are my pros:&lt;/p&gt;\n\n&lt;blockquote&gt;\n&lt;p&gt;battery is superior(a bit better compared to my wife&amp;#39;s s23u)\nphone speaker is top notch\ncamera operation is faster and transition between lenses is more fluid\ncamera quality when on social media apps are much better(i dont use it but it&amp;#39;s better)\nalways on display is much better&lt;/p&gt;\n&lt;/blockquote&gt;\n\n&lt;p&gt;Cons:&lt;/p&gt;\n\n&lt;blockquote&gt;\n&lt;p&gt;no universal back gesture (Can&amp;#39;t use one hand properly because of this. Always have to reach for the top left to go back. Funny thing is it&amp;#39;s not even consistent, sometimes it&amp;#39;s on the lower left on some apps\nplacement of the action button makes it useless. It&amp;#39;s in a hard to reach spot when using one hand so it&amp;#39;s faster to just open the phone\nHome screen is a mess. You can grouo them into folders but still a mess and harder to organize vs Oneui\nSeveral times i&amp;#39;ve had issues receiving a text. I tested it by sending a text message from s23u and i would receive the message after maybe 5 mins. When i reply back, the s23u would receive it right away\nnotification center is a mess compared to one ui&amp;#39;s or any androids\nalways have to go to Settings app to change settings from some apps\nin my use case I think fingerprint is more convenient than face id. When working and want to check something from my phone lying on the table, I hate that i have to bring it up and face id vs just using fingerprint\ns23u feels snappier. Yes it does. Faster swipes and the screen refresh rate is more consistently at 120hz than my 15pm&lt;/p&gt;\n&lt;/blockquote&gt;\n\n&lt;p&gt;I just think you can do things faster on one ui and it&amp;#39;s easier to use one handed even considering the latest oneui update where the drop down menu pushed some things higher. &lt;/p&gt;\n\n&lt;p&gt;I&amp;#39;m debating on returning my phone and wait for the s24u. Or maybe im just too used to oneui and i need to spend more time on ios.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
    numberOfComments: 209,
    flair: "OneUI",
    upVotes: 243,
    upVoteRatio: 0.87,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl: "self",
    createdAt: "2024-01-03T15:32:12.000Z",
    scrapedAt: "2024-10-13T18:30:51.007Z",
    dataType: "post",
  },
  {
    id: "t1_lm6f26h",
    parsedId: "lm6f26h",
    url: "https://www.reddit.com/r/apple/comments/1fc5o8w/apple_set_to_unveil_iphone_16_on_monday_heres/lm6f26h/",
    postId: "t3_1fc5o8w",
    parentId: "t1_lm6dd77",
    username: "Cheeetooos",
    userId: "t2_wttci",
    category: "apple",
    communityName: "r/apple",
    body: "That’s another factor for me actually. My grandma needs a “new” phone.",
    createdAt: "2024-09-08T21:06:02.000Z",
    scrapedAt: "2024-10-13T18:30:50.402Z",
    upVotes: 114,
    numberOfreplies: 4,
    html: '&lt;div class="md"&gt;&lt;p&gt;That’s another factor for me actually. My grandma needs a “new” phone.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_lm6f7f6",
    parsedId: "lm6f7f6",
    url: "https://www.reddit.com/r/apple/comments/1fc5o8w/apple_set_to_unveil_iphone_16_on_monday_heres/lm6f7f6/",
    postId: "t3_1fc5o8w",
    parentId: "t1_lm6f26h",
    username: "whatever604",
    userId: "t2_idkrv",
    category: "apple",
    communityName: "r/apple",
    body: "You’re just being a good grandson",
    createdAt: "2024-09-08T21:06:47.000Z",
    scrapedAt: "2024-10-13T18:30:50.402Z",
    upVotes: 79,
    numberOfreplies: 2,
    html: '&lt;div class="md"&gt;&lt;p&gt;You’re just being a good grandson&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_kg50twc",
    parsedId: "kg50twc",
    url: "https://www.reddit.com/r/samsung/comments/18xm33x/just_switched_to_iphone_and_regret_it/kg50twc/",
    postId: "t3_18xm33x",
    parentId: "t3_18xm33x",
    username: "NefariousnessJaded87",
    userId: "t2_b4pky2n5",
    category: "samsung",
    communityName: "r/samsung",
    body: "Sorry for your problems and loss of a good unit.",
    createdAt: "2024-01-03T15:52:11.000Z",
    scrapedAt: "2024-10-13T18:30:51.206Z",
    upVotes: 87,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;Sorry for your problems and loss of a good unit.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_kg5aua8",
    parsedId: "kg5aua8",
    url: "https://www.reddit.com/r/samsung/comments/18xm33x/just_switched_to_iphone_and_regret_it/kg5aua8/",
    postId: "t3_18xm33x",
    parentId: "t3_18xm33x",
    username: "Yoshaay",
    userId: "t2_8bbd2mhl",
    category: "samsung",
    communityName: "r/samsung",
    body: "I couldn't go to IOS simply because of no APKs",
    createdAt: "2024-01-03T16:53:10.000Z",
    scrapedAt: "2024-10-13T18:30:51.206Z",
    upVotes: 162,
    numberOfreplies: 11,
    html: '&lt;div class="md"&gt;&lt;p&gt;I couldn&amp;#39;t go to IOS simply because of no APKs&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_kg5dhpz",
    parsedId: "kg5dhpz",
    url: "https://www.reddit.com/r/samsung/comments/18xm33x/just_switched_to_iphone_and_regret_it/kg5dhpz/",
    postId: "t3_18xm33x",
    parentId: "t1_kg5aua8",
    username: "stayloa",
    userId: "t2_3ocqz",
    category: "samsung",
    communityName: "r/samsung",
    body: "100% this for me. Not bashing Apple at all - they're insanely good at what they do, and their phones are amazing for the majority of people. If you want to super customise or sideload stuff though, Android all the way.",
    createdAt: "2024-01-03T17:10:02.000Z",
    scrapedAt: "2024-10-13T18:30:51.206Z",
    upVotes: 90,
    numberOfreplies: 5,
    html: '&lt;div class="md"&gt;&lt;p&gt;100% this for me. Not bashing Apple at all - they&amp;#39;re insanely good at what they do, and their phones are amazing for the majority of people. If you want to super customise or sideload stuff though, Android all the way.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_kg680sd",
    parsedId: "kg680sd",
    url: "https://www.reddit.com/r/samsung/comments/18xm33x/just_switched_to_iphone_and_regret_it/kg680sd/",
    postId: "t3_18xm33x",
    parentId: "t1_kg5dhpz",
    username: "truthtakest1me",
    userId: "t2_hoxv0oh0s",
    category: "samsung",
    communityName: "r/samsung",
    body: "This is always said but every time I see threads with Home Screen setups they’re ugly AF.",
    createdAt: "2024-01-03T20:03:07.000Z",
    scrapedAt: "2024-10-13T18:30:51.206Z",
    upVotes: 23,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;This is always said but every time I see threads with Home Screen setups they’re ugly AF.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_18lkpck",
    parsedId: "18lkpck",
    url: "https://www.reddit.com/r/iphone/comments/18lkpck/just_got_my_first_iphone_any_tips/",
    username: "Jyri5v",
    userId: "t2_60fxoqb7",
    title: "Just got my first iphone. Any tips?",
    communityName: "r/iphone",
    parsedCommunityName: "iphone",
    body: "I recently made the switch to my first iPhone, the iPhone 13 Pro, after using Android phones for over a decade. As a newbie to the iPhone world, I'm curious if there is any good tips that I should change right away in the settings that could possibly make my everyday life better?",
    html: '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;I recently made the switch to my first iPhone, the iPhone 13 Pro, after using Android phones for over a decade. As a newbie to the iPhone world, I&amp;#39;m curious if there is any good tips that I should change right away in the settings that could possibly make my everyday life better?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
    numberOfComments: 176,
    flair: "Discussion",
    upVotes: 187,
    upVoteRatio: 0.85,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl: "self",
    createdAt: "2023-12-18T21:53:26.000Z",
    scrapedAt: "2024-10-13T18:30:51.508Z",
    dataType: "post",
  },
  {
    id: "t1_kg9uewg",
    parsedId: "kg9uewg",
    url: "https://www.reddit.com/r/samsung/comments/18xm33x/just_switched_to_iphone_and_regret_it/kg9uewg/",
    postId: "t3_18xm33x",
    parentId: "t1_kg680sd",
    username: "Live-Coyote-596",
    userId: "t2_api5r1vh",
    category: "samsung",
    communityName: "r/samsung",
    body: "But at least you have the choice to have an ugly home screen.",
    createdAt: "2024-01-04T13:06:08.000Z",
    scrapedAt: "2024-10-13T18:30:51.206Z",
    upVotes: 4,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;But at least you have the choice to have an ugly home screen.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_kdznb2j",
    parsedId: "kdznb2j",
    url: "https://www.reddit.com/r/iphone/comments/18lkpck/just_got_my_first_iphone_any_tips/kdznb2j/",
    postId: "t3_18lkpck",
    parentId: "t3_18lkpck",
    username: "mngdew",
    userId: "t2_w47g6",
    category: "iphone",
    communityName: "r/iphone",
    body: "Don’t get obsessed with battery health.",
    createdAt: "2023-12-19T03:39:11.000Z",
    scrapedAt: "2024-10-13T18:30:51.603Z",
    upVotes: 314,
    numberOfreplies: 3,
    html: '&lt;div class="md"&gt;&lt;p&gt;Don’t get obsessed with battery health.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_1fcwwyc",
    parsedId: "1fcwwyc",
    url: "https://www.reddit.com/r/iphone/comments/1fcwwyc/apple_discontinues_iphone_13_following_iphone_16/",
    username: "PJ09",
    userId: "t2_th4cg",
    title: "Apple discontinues iPhone 13 following iPhone 16 launch",
    communityName: "r/iphone",
    parsedCommunityName: "iphone",
    body: "URL: https://9to5mac.com/2024/09/09/apple-discontinues-iphones/\nThumbnail: https://b.thumbs.redditmedia.com/wJJIw5VYinx0fi_aS_Ij6NH6C5Y8078Ko-3REAbAT1c.jpg\nImages:\n\thttps://external-preview.redd.it/b0th5cPe1418zNyi-kcjq-gL303LAUUFqQwaWGVvvn4.jpg?auto=webp&amp;s=f1deea542dd2f41f95479d83f011298e4bb89c76\n",
    html: null,
    numberOfComments: 155,
    flair: "News/Rumour",
    upVotes: 689,
    upVoteRatio: 0.98,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl:
      "https://b.thumbs.redditmedia.com/wJJIw5VYinx0fi_aS_Ij6NH6C5Y8078Ko-3REAbAT1c.jpg",
    createdAt: "2024-09-09T18:42:14.000Z",
    scrapedAt: "2024-10-13T18:30:51.619Z",
    dataType: "post",
  },
];
