export const rawData = [
  {
    kind: "youtube#searchResult",
    etag: "2JasxlistNqsMCdiiuDLJPErIcU",
    id: {
      kind: "youtube#video",
      videoId: "wxt77goIlXo",
    },
    snippet: {
      publishedAt: "2024-10-12T17:07:09Z",
      channelId: "UCq29tGmaqaKhChzbIHHNyqQ",
      title:
        "EASY ORANGE DRAWING, #easy #easydrawing #beginners #painting #artandcraft #art #drawingideas #diy",
      description:
        "EASY ORANGE DRAWING, #easy #easydrawing #beginners #painting #artandcraft #art #drawingideas #diy.",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/wxt77goIlXo/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/wxt77goIlXo/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/wxt77goIlXo/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "try it out",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T17:07:09Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "naEynmBsO1SYDASsn9fI4Mvi3pM",
    id: {
      kind: "youtube#video",
      videoId: "wWmAmGQdOu0",
    },
    snippet: {
      publishedAt: "2024-10-12T14:00:50Z",
      channelId: "UCw1lCaqwNbS34e235eVEyWQ",
      title: "Solved a Rubik&#39;s Cube color Orange",
      description: "",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/wWmAmGQdOu0/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/wWmAmGQdOu0/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/wWmAmGQdOu0/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "The Fighter",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T14:00:50Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "L7V3JMDIb8oLVMf_r0Tt-bu3pC4",
    id: {
      kind: "youtube#video",
      videoId: "oSfFfuuGxYI",
    },
    snippet: {
      publishedAt: "2024-10-12T13:42:13Z",
      channelId: "UCD8yoDPxz0id8OgGCRPiVIw",
      title: "ഇത്രയും ചെറിയ മരത്തിൽ orange ഇതുപോലെ കായിക്കുമോ? ടിപ്സ്.",
      description:
        "ഇത്രയും ചെറിയ മരത്തിൽ orange ഇതുപോലെ കായിക്കുമോ? ടിപ്സ്. Can an orange bear ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/oSfFfuuGxYI/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/oSfFfuuGxYI/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/oSfFfuuGxYI/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Rose Garden",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T13:42:13Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "t09cx-DC0QGHC8cvClLHFXcQj9c",
    id: {
      kind: "youtube#video",
      videoId: "wZGKufDhm70",
    },
    snippet: {
      publishedAt: "2024-10-12T13:03:16Z",
      channelId: "UCBfDfKIepnqC5pnWCAKikSg",
      title: "Orange ka real colour       #facts #factinhindi #factshorts",
      description: "Orange ka real colour #facts #factinhindi #factshorts.",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/wZGKufDhm70/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/wZGKufDhm70/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/wZGKufDhm70/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "TechMeraz ",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T13:03:16Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "2uT0VRrfryJ17oCsXBxWdBahIjM",
    id: {
      kind: "youtube#video",
      videoId: "qbSfTazMxkI",
    },
    snippet: {
      publishedAt: "2024-10-12T12:50:42Z",
      channelId: "UCBAVeOwX9GupXekfAp0J1oA",
      title: "If You Eat 1 Orange Every Day This Is What Happens To Your Body",
      description:
        "If You Eat 1 Orange Every Day This Is What Happens To Your Body #oranges #keto #ketodiet #weightloss #ketolifestyle ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/qbSfTazMxkI/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/qbSfTazMxkI/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/qbSfTazMxkI/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Diet Zone",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T12:50:42Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "DBcFlpICrzTRoONa4AywqzJTigA",
    id: {
      kind: "youtube#video",
      videoId: "2pVpngmH9bc",
    },
    snippet: {
      publishedAt: "2024-10-12T12:33:45Z",
      channelId: "UCWnnmlIKF975UuXGjc0TWmQ",
      title:
        "Get Glowing Skin with ORANGE PEEL! (Vitamin C Serum Hack) [2024]#shorts",
      description:
        "Unlock the secret to radiant, glowing skin with our latest DIY hack using orange peel! In this video, we'll show you how to create a ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/2pVpngmH9bc/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/2pVpngmH9bc/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/2pVpngmH9bc/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "The Ai Tara",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T12:33:45Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "2OrQT8DM99NY6jRowXCukRIGy98",
    id: {
      kind: "youtube#video",
      videoId: "zNK2da8K3ZM",
    },
    snippet: {
      publishedAt: "2024-10-12T12:01:16Z",
      channelId: "UC3S6nIDGJ5OtpC-mbvFA8Ew",
      title: "I Maxed out the Lavaloon Puppet",
      description:
        "New Halloween event in 2024. New hero equipment the Lavaloon puppet. Witch Golem, Barcher, Hog Wizard, Ice Minion and ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/zNK2da8K3ZM/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/zNK2da8K3ZM/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/zNK2da8K3ZM/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Orange Juice Gaming",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T12:01:16Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "vWtlNQok2IDchyq_9XMRzZtsMro",
    id: {
      kind: "youtube#video",
      videoId: "5u8UXyW7fDA",
    },
    snippet: {
      publishedAt: "2024-10-12T11:15:36Z",
      channelId: "UCm3cpXx3A7Lb3GgkcGYUV7g",
      title:
        "Orange peel home made face mask😍😍#trendingshorts #skincare #skincaretips #homemade #beauty",
      description:
        "Orange peel home made face mask    #trendingshorts #skincare #skincaretips #homemade #beauty.",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/5u8UXyW7fDA/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/5u8UXyW7fDA/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/5u8UXyW7fDA/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Anjum",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T11:15:36Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "1aHnDzaUL0rdTDpwCQBCERby67c",
    id: {
      kind: "youtube#video",
      videoId: "hFGhguimKHg",
    },
    snippet: {
      publishedAt: "2024-10-12T10:24:57Z",
      channelId: "UCCl62oBQfjUAjBg3AKYt7Ww",
      title: "how to draw an orange - Part 2 drawing fruits",
      description: "",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/hFGhguimKHg/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/hFGhguimKHg/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/hFGhguimKHg/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "colouring and drawing ",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T10:24:57Z",
    },
  },
  {
    kind: "youtube#searchResult",
    etag: "-yVeJBW1CAeAkjirMKrVeTo21vA",
    id: {
      kind: "youtube#video",
      videoId: "Ytsy15xLtgc",
    },
    snippet: {
      publishedAt: "2024-10-12T07:56:26Z",
      channelId: "UCYRJN1hoKPJ0GuQy7m5tWSw",
      title:
        "ORANGE QUILL |  SPIRITBORN RANK 1 PUSH | 150+ Beta Hours | GOBLIN-Inc | #Diablo4 | !youtube …",
      description:
        "Build: https://tinyurl.com/577yjt2e Twitch: https://www.twitch.tv/aceofspadeshots Mid Game: https://tinyurl.com/wmu9vd67 Leveling ...",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/Ytsy15xLtgc/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/Ytsy15xLtgc/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/Ytsy15xLtgc/hqdefault.jpg",
          width: 480,
          height: 360,
        },
      },
      channelTitle: "Goblin Inc.",
      liveBroadcastContent: "none",
      publishTime: "2024-10-12T07:56:26Z",
    },
  },
];

export const redditData = [
  {
    id: "t3_pf72ap",
    parsedId: "pf72ap",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/pf72ap/why_is_your_name_so_popular/",
    username: "[deleted]",
    title: "Why is Your Name so popular?",
    communityName: "r/KimiNoNaWa",
    parsedCommunityName: "KimiNoNaWa",
    body: "I understand that the animation, art and music is amazing, but I don't understand why people were so attach to the plot/characters. Can u guys give me some reasons why?",
    html: '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;I understand that the animation, art and music is amazing, but I don&amp;#39;t understand why people were so attach to the plot/characters. Can u guys give me some reasons why?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
    numberOfComments: 29,
    flair: "Discussion",
    upVotes: 60,
    upVoteRatio: 0.92,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl: "self",
    createdAt: "2021-08-31T14:33:13.000Z",
    scrapedAt: "2024-10-13T19:31:14.127Z",
    dataType: "post",
  },
  {
    id: "t1_hb2a7ja",
    parsedId: "hb2a7ja",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/pf72ap/why_is_your_name_so_popular/hb2a7ja/",
    postId: "t3_pf72ap",
    parentId: "t3_pf72ap",
    username: "[deleted]",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "For me, the plot was really engaging. It was like a breath of fresh air. I’d never seen a movie anything like Your Name before. The twist(3-year gap and the comet) was rather shocking, and all the events that came subsequently was really what captivated me. The execution of the story was nearly flawless. Sure, there are a few plot holes here and there but a rewatch is sure to paint a more clear and vivid picture in your head.\nI believe Makoto Shinkai has done a splendid job with Your name. He truly is a phenomenal storyteller.",
    createdAt: "2021-08-31T14:46:52.000Z",
    scrapedAt: "2024-10-13T19:31:14.189Z",
    upVotes: 39,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;For me, the plot was really engaging. It was like a breath of fresh air. I’d never seen a movie anything like Your Name before. The twist(3-year gap and the comet) was rather shocking, and all the events that came subsequently was really what captivated me. The execution of the story was nearly flawless. Sure, there are a few plot holes here and there but a rewatch is sure to paint a more clear and vivid picture in your head.\nI believe Makoto Shinkai has done a splendid job with Your name. He truly is a phenomenal storyteller.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_hb2gjzf",
    parsedId: "hb2gjzf",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/pf72ap/why_is_your_name_so_popular/hb2gjzf/",
    postId: "t3_pf72ap",
    parentId: "t3_pf72ap",
    username: "AnotherBrock",
    userId: "t2_2i0j2kv2",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "It played with my feelings like no other movie had ever before",
    createdAt: "2021-08-31T15:29:58.000Z",
    scrapedAt: "2024-10-13T19:31:14.189Z",
    upVotes: 33,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;It played with my feelings like no other movie had ever before&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_hb2c7pb",
    parsedId: "hb2c7pb",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/pf72ap/why_is_your_name_so_popular/hb2c7pb/",
    postId: "t3_pf72ap",
    parentId: "t3_pf72ap",
    username: "alandragonrojo",
    userId: "t2_662s6zz6",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "I love Makoto Shinkai's stories, their characters are complex, but the storytelling is very sutil, the first time that I saw The Garden of Words, I couldn't understand it's complexity at once, so I think the way he writes is sublime, and your name is like The next step, it has complex characters, but in some way the story is more easy to enjoy without too much analysis, so I think this last part is what makes it popular.\n\nAlso the first time that I saw it I thought it was the typical change of body story, but it is much more.",
    createdAt: "2021-08-31T15:00:34.000Z",
    scrapedAt: "2024-10-13T19:31:14.189Z",
    upVotes: 20,
    numberOfreplies: 2,
    html: '&lt;div class="md"&gt;&lt;p&gt;I love Makoto Shinkai&amp;#39;s stories, their characters are complex, but the storytelling is very sutil, the first time that I saw The Garden of Words, I couldn&amp;#39;t understand it&amp;#39;s complexity at once, so I think the way he writes is sublime, and your name is like The next step, it has complex characters, but in some way the story is more easy to enjoy without too much analysis, so I think this last part is what makes it popular.&lt;/p&gt;\n\n&lt;p&gt;Also the first time that I saw it I thought it was the typical change of body story, but it is much more.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_hb2fkx1",
    parsedId: "hb2fkx1",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/pf72ap/why_is_your_name_so_popular/hb2fkx1/",
    postId: "t3_pf72ap",
    parentId: "t1_hb2c7pb",
    username: "[deleted]",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "I couldn't have said it any better myself. I actually had the same thoughts as you at the start, but the transition from a happy, upbeat film to an emotional one was done perfectly and it's one of the reasons why I love this film.",
    createdAt: "2021-08-31T15:23:24.000Z",
    scrapedAt: "2024-10-13T19:31:14.189Z",
    upVotes: 11,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;I couldn&amp;#39;t have said it any better myself. I actually had the same thoughts as you at the start, but the transition from a happy, upbeat film to an emotional one was done perfectly and it&amp;#39;s one of the reasons why I love this film.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_hb2qiuu",
    parsedId: "hb2qiuu",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/pf72ap/why_is_your_name_so_popular/hb2qiuu/",
    postId: "t3_pf72ap",
    parentId: "t1_hb2c7pb",
    username: "firefistzoro",
    userId: "t2_w4itt",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "I would actually disagree that the characters are complex, Mitsuha is by far the strongest character and carries a lot of the emotional core herself (well it's more the connection shared between them) but I wouldn't say she's overally complex. Taki, like most of Shinkai's male leads, are pretty repalceable, forgettable and generic. \n\nI don't necessarily find that that detracts from the film though. Sure, if Taki had his own character arc that tied in with the plot/story that could make it even better. I saw someone criticise Shinkai of doing 'melodramas' and that's pretty accurate; he focuses more on outlandish plots (at least in Your Name) and evoking emotions rather than characterisation. And for Your Name I think that works just fine.\n\nI think Shinkai successfully manages to convey the 'feeling' and evoke emotions that were universally felt, though not necessarily fully grasped; there wasn't meant to be a concrete message or a specific philosophy that shaped the narrative (kind of what you were saying about an easy to enjoy story). We all feel the emptiness and melancholia of the connection they share being lost to time and space... he takes some shortcuts with the plot and exposition in order to convey these feelings but I think I can forgive it given how successfully and how powerful the emotions he delivered to the viewer were.",
    createdAt: "2021-08-31T16:36:57.000Z",
    scrapedAt: "2024-10-13T19:31:14.189Z",
    upVotes: 6,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;I would actually disagree that the characters are complex, Mitsuha is by far the strongest character and carries a lot of the emotional core herself (well it&amp;#39;s more the connection shared between them) but I wouldn&amp;#39;t say she&amp;#39;s overally complex. Taki, like most of Shinkai&amp;#39;s male leads, are pretty repalceable, forgettable and generic. &lt;/p&gt;\n\n&lt;p&gt;I don&amp;#39;t necessarily find that that detracts from the film though. Sure, if Taki had his own character arc that tied in with the plot/story that could make it even better. I saw someone criticise Shinkai of doing &amp;#39;melodramas&amp;#39; and that&amp;#39;s pretty accurate; he focuses more on outlandish plots (at least in Your Name) and evoking emotions rather than characterisation. And for Your Name I think that works just fine.&lt;/p&gt;\n\n&lt;p&gt;I think Shinkai successfully manages to convey the &amp;#39;feeling&amp;#39; and evoke emotions that were universally felt, though not necessarily fully grasped; there wasn&amp;#39;t meant to be a concrete message or a specific philosophy that shaped the narrative (kind of what you were saying about an easy to enjoy story). We all feel the emptiness and melancholia of the connection they share being lost to time and space... he takes some shortcuts with the plot and exposition in order to convey these feelings but I think I can forgive it given how successfully and how powerful the emotions he delivered to the viewer were.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_1aqxm8m",
    parsedId: "1aqxm8m",
    url: "https://www.reddit.com/r/anime/comments/1aqxm8m/suzume_was_amazing_and_your_name_was_even_better/",
    username: "Senornerdpodcast",
    userId: "t2_57hhg4e2c",
    title: '"Suzume" was Amazing and "Your Name" was even better.',
    communityName: "r/anime",
    parsedCommunityName: "anime",
    body: 'We just recently saw Suzume and we love it!! This week we saw "Your Name" and was blown away by the story telling in the movie. Seriously hope we get to see "Weathering with You" soon. What are your rankings of these movies?',
    html: '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;We just recently saw Suzume and we love it!! This week we saw &amp;quot;Your Name&amp;quot; and was blown away by the story telling in the movie. Seriously hope we get to see &amp;quot;Weathering with You&amp;quot; soon. What are your rankings of these movies?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
    numberOfComments: 177,
    flair: "Discussion",
    upVotes: 413,
    upVoteRatio: 0.85,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl: "self",
    createdAt: "2024-02-14T20:58:06.000Z",
    scrapedAt: "2024-10-13T19:31:17.505Z",
    dataType: "post",
  },
  {
    id: "t1_kqglqvu",
    parsedId: "kqglqvu",
    url: "https://www.reddit.com/r/anime/comments/1aqxm8m/suzume_was_amazing_and_your_name_was_even_better/kqglqvu/",
    postId: "t3_1aqxm8m",
    parentId: "t3_1aqxm8m",
    username: "I_BEAT_JUMP_ATTACHED",
    userId: "t2_47y768gq",
    category: "anime",
    communityName: "r/anime",
    body: "Maybe a hot take but I thought Suzume was trying to do way too many things in too short a span of time. It was trying to be adventure, romance, family problems, and more in just a short movie. So it did everything decently, but nothing well.",
    createdAt: "2024-02-14T23:53:50.000Z",
    scrapedAt: "2024-10-13T19:31:17.604Z",
    upVotes: 101,
    numberOfreplies: 5,
    html: '&lt;div class="md"&gt;&lt;p&gt;Maybe a hot take but I thought Suzume was trying to do way too many things in too short a span of time. It was trying to be adventure, romance, family problems, and more in just a short movie. So it did everything decently, but nothing well.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_kqior3r",
    parsedId: "kqior3r",
    url: "https://www.reddit.com/r/anime/comments/1aqxm8m/suzume_was_amazing_and_your_name_was_even_better/kqior3r/",
    postId: "t3_1aqxm8m",
    parentId: "t1_kqglqvu",
    username: "Psclly",
    userId: "t2_13lsd2",
    category: "anime",
    communityName: "r/anime",
    body: "I guess thats also why Your Name was so goddamm good. It was the opposite of what you said about Suzume. It focussed on a singular theme and just went for it through and through.",
    createdAt: "2024-02-15T11:10:09.000Z",
    scrapedAt: "2024-10-13T19:31:17.604Z",
    upVotes: 43,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;I guess thats also why Your Name was so goddamm good. It was the opposite of what you said about Suzume. It focussed on a singular theme and just went for it through and through.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_kqjvhlw",
    parsedId: "kqjvhlw",
    url: "https://www.reddit.com/r/anime/comments/1aqxm8m/suzume_was_amazing_and_your_name_was_even_better/kqjvhlw/",
    postId: "t3_1aqxm8m",
    parentId: "t1_kqglqvu",
    username: "NarejED",
    userId: "t2_s0fre",
    category: "anime",
    communityName: "r/anime",
    body: "It definitely fell apart in the second half. The guardians, worm, and numerous other things were never properly explained and felt more like set dressing than actual plot. Everything after the scene with the door in the pool was downhill for me. Visually stunning but definitely not the creator's best work.",
    createdAt: "2024-02-15T16:25:54.000Z",
    scrapedAt: "2024-10-13T19:31:17.604Z",
    upVotes: 15,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;It definitely fell apart in the second half. The guardians, worm, and numerous other things were never properly explained and felt more like set dressing than actual plot. Everything after the scene with the door in the pool was downhill for me. Visually stunning but definitely not the creator&amp;#39;s best work.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_kqk1d7b",
    parsedId: "kqk1d7b",
    url: "https://www.reddit.com/r/anime/comments/1aqxm8m/suzume_was_amazing_and_your_name_was_even_better/kqk1d7b/",
    postId: "t3_1aqxm8m",
    parentId: "t1_kqjvhlw",
    username: "I_BEAT_JUMP_ATTACHED",
    userId: "t2_47y768gq",
    category: "anime",
    communityName: "r/anime",
    body: "Also, one of the two main characters was literally a chair for 2/3 of the movie.",
    createdAt: "2024-02-15T16:59:20.000Z",
    scrapedAt: "2024-10-13T19:31:17.604Z",
    upVotes: 11,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;Also, one of the two main characters was literally a chair for 2/3 of the movie.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_kqit0je",
    parsedId: "kqit0je",
    url: "https://www.reddit.com/r/anime/comments/1aqxm8m/suzume_was_amazing_and_your_name_was_even_better/kqit0je/",
    postId: "t3_1aqxm8m",
    parentId: "t1_kqglqvu",
    username: "bdfariello",
    userId: "t2_3cmnr",
    category: "anime",
    communityName: "r/anime",
    body: "Suzume was the result of a bet that he couldn't make girls across the entire world fall in love with [Suzume] &gt;!a chair!&lt;",
    createdAt: "2024-02-15T11:55:30.000Z",
    scrapedAt: "2024-10-13T19:31:17.604Z",
    upVotes: 6,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;Suzume was the result of a bet that he couldn&amp;#39;t make girls across the entire world fall in love with [Suzume] &lt;span class="md-spoiler-text"&gt;a chair&lt;/span&gt;&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_in73xm",
    parsedId: "in73xm",
    url: "https://www.reddit.com/r/anime/comments/in73xm/this_will_never_not_be_funny_to_me_your_name/",
    username: "fatima12798",
    userId: "t2_36postor",
    title: "This will never not be funny to me (Your name)",
    communityName: "r/anime",
    parsedCommunityName: "anime",
    body: "URL: https://v.redd.it/sl4ij9zaqdl51\nThumbnail: https://b.thumbs.redditmedia.com/pMODAo-XCVC7KAPwhX8EQgMbvuEiNF_lbdubBRDbS0o.jpg\nImages:\n\thttps://external-preview.redd.it/7HmChujnsD_JS2T2OgYJM1i-rXEeoJrlWLm5IlujsZ0.png?format=pjpg&amp;auto=webp&amp;s=b48131937e825ef97ac8f40f5fce0e7f1883494a\n",
    html: null,
    numberOfComments: 476,
    flair: "Clip",
    upVotes: 20410,
    upVoteRatio: 0.98,
    isVideo: true,
    isAd: false,
    over18: false,
    videoUrl: "https://v.redd.it/sl4ij9zaqdl51/DASH_720.mp4?source=fallback",
    thumbnailUrl:
      "https://b.thumbs.redditmedia.com/pMODAo-XCVC7KAPwhX8EQgMbvuEiNF_lbdubBRDbS0o.jpg",
    createdAt: "2020-09-05T19:20:48.000Z",
    scrapedAt: "2024-10-13T19:31:18.405Z",
    dataType: "post",
  },
  {
    id: "t1_g45nlte",
    parsedId: "g45nlte",
    url: "https://www.reddit.com/r/anime/comments/in73xm/this_will_never_not_be_funny_to_me_your_name/g45nlte/",
    postId: "t3_in73xm",
    parentId: "t3_in73xm",
    username: "Ijaccb",
    userId: "t2_5t3sgk0n",
    category: "anime",
    communityName: "r/anime",
    body: "I think about this a lot",
    createdAt: "2020-09-05T19:33:25.000Z",
    scrapedAt: "2024-10-13T19:31:18.428Z",
    upVotes: 2676,
    numberOfreplies: 4,
    html: '&lt;div class="md"&gt;&lt;p&gt;I think about this a lot&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_g45uah2",
    parsedId: "g45uah2",
    url: "https://www.reddit.com/r/anime/comments/in73xm/this_will_never_not_be_funny_to_me_your_name/g45uah2/",
    postId: "t3_in73xm",
    parentId: "t1_g45nlte",
    username: "Orion_Hammer",
    userId: "t2_14bp0q",
    category: "anime",
    communityName: "r/anime",
    body: "It’s a pretty funny language specific joke. I think they did their best bringing it to English but that’s a hard one. [(sub and dub of the same scene)](https://youtu.be/iowh6UxahKs)",
    createdAt: "2020-09-05T20:28:14.000Z",
    scrapedAt: "2024-10-13T19:31:18.428Z",
    upVotes: 2330,
    numberOfreplies: 6,
    html: '&lt;div class="md"&gt;&lt;p&gt;It’s a pretty funny language specific joke. I think they did their best bringing it to English but that’s a hard one. &lt;a href="https://youtu.be/iowh6UxahKs"&gt;(sub and dub of the same scene)&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_g45ym9m",
    parsedId: "g45ym9m",
    url: "https://www.reddit.com/r/anime/comments/in73xm/this_will_never_not_be_funny_to_me_your_name/g45ym9m/",
    postId: "t3_in73xm",
    parentId: "t1_g45uah2",
    username: "YanderesHaveMyHeart",
    userId: "t2_55s5ncp7",
    category: "anime",
    communityName: "r/anime",
    body: "Honestly it wasn't handled that bad.",
    createdAt: "2020-09-05T21:01:57.000Z",
    scrapedAt: "2024-10-13T19:31:18.428Z",
    upVotes: 1129,
    numberOfreplies: 3,
    html: '&lt;div class="md"&gt;&lt;p&gt;Honestly it wasn&amp;#39;t handled that bad.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_g45zznv",
    parsedId: "g45zznv",
    url: "https://www.reddit.com/r/anime/comments/in73xm/this_will_never_not_be_funny_to_me_your_name/g45zznv/",
    postId: "t3_in73xm",
    parentId: "t1_g45ym9m",
    username: "Orion_Hammer",
    userId: "t2_14bp0q",
    category: "anime",
    communityName: "r/anime",
    body: "Your right! To clarify I think they did a great job on that movie. 😁",
    createdAt: "2020-09-05T21:13:00.000Z",
    scrapedAt: "2024-10-13T19:31:18.428Z",
    upVotes: 481,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;Your right! To clarify I think they did a great job on that movie. 😁&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_g46dsk3",
    parsedId: "g46dsk3",
    url: "https://www.reddit.com/r/anime/comments/in73xm/this_will_never_not_be_funny_to_me_your_name/g46dsk3/",
    postId: "t3_in73xm",
    parentId: "t1_g45zznv",
    username: "gartontomas",
    userId: "t2_2ri49eor",
    category: "anime",
    communityName: "r/anime",
    body: "The movie was fucking amazing overall, definitely one of my favourites",
    createdAt: "2020-09-05T23:04:01.000Z",
    scrapedAt: "2024-10-13T19:31:18.428Z",
    upVotes: 199,
    numberOfreplies: 2,
    html: '&lt;div class="md"&gt;&lt;p&gt;The movie was fucking amazing overall, definitely one of my favourites&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_63yjc7",
    parsedId: "63yjc7",
    url: "https://www.reddit.com/r/movies/comments/63yjc7/official_discussion_your_name_spoilers/",
    username: "LiteraryBoner",
    userId: "t2_54xmx",
    title: "Official Discussion: Your Name [SPOILERS]",
    communityName: "r/movies",
    parsedCommunityName: "movies",
    body: "**Poll**\n\n\n\n**If you've seen the film, please rate it [at this poll.](https://youpoll.me/2983/)**\n\n\n**If you haven't seen the film but would like to see the result of the poll [click here.](https://youpoll.me/2983/r)**\n\n\n**Summary:** Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?\n\n\n**Director:** Makoto Shinkai\n\n\n**Writers:** Makoto Shinkai\n\n\n**Cast:**\n\n* Michael Sinterniklaas as Taki Tachibana\n* Stephanie Sheh as Mitsuha Miyamizu\n* Kyle Hebert as Katsuhiko Teshigawara\n* Cassandra Morris as Sayaka Natori \n* Ben Pronsky as Tsukasa Fujii \n* Ray Chase as Shinta Takagi\n* Catie Harvey as Yotsuha Miyamizu\n\n\n**Rotten Tomatoes:** [97%](https://www.rottentomatoes.com/m/your_name_2017)\n\n\n**Metacritic:** [78/100](http://www.metacritic.com/movie/your-name)\n\n\n**After Credits Scene?:** No",
    html: '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;&lt;strong&gt;Poll&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;If you&amp;#39;ve seen the film, please rate it &lt;a href="https://youpoll.me/2983/"&gt;at this poll.&lt;/a&gt;&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;If you haven&amp;#39;t seen the film but would like to see the result of the poll &lt;a href="https://youpoll.me/2983/r"&gt;click here.&lt;/a&gt;&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;Summary:&lt;/strong&gt; Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;Director:&lt;/strong&gt; Makoto Shinkai&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;Writers:&lt;/strong&gt; Makoto Shinkai&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;Cast:&lt;/strong&gt;&lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;Michael Sinterniklaas as Taki Tachibana&lt;/li&gt;\n&lt;li&gt;Stephanie Sheh as Mitsuha Miyamizu&lt;/li&gt;\n&lt;li&gt;Kyle Hebert as Katsuhiko Teshigawara&lt;/li&gt;\n&lt;li&gt;Cassandra Morris as Sayaka Natori &lt;/li&gt;\n&lt;li&gt;Ben Pronsky as Tsukasa Fujii &lt;/li&gt;\n&lt;li&gt;Ray Chase as Shinta Takagi&lt;/li&gt;\n&lt;li&gt;Catie Harvey as Yotsuha Miyamizu&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;&lt;strong&gt;Rotten Tomatoes:&lt;/strong&gt; &lt;a href="https://www.rottentomatoes.com/m/your_name_2017"&gt;97%&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;Metacritic:&lt;/strong&gt; &lt;a href="http://www.metacritic.com/movie/your-name"&gt;78/100&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;After Credits Scene?:&lt;/strong&gt; No&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
    numberOfComments: 1070,
    flair: null,
    upVotes: 1908,
    upVoteRatio: 0.95,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl: "self",
    createdAt: "2017-04-07T05:31:40.000Z",
    scrapedAt: "2024-10-13T19:31:20.596Z",
    dataType: "post",
  },
  {
    id: "t1_dfysl4l",
    parsedId: "dfysl4l",
    url: "https://www.reddit.com/r/movies/comments/63yjc7/official_discussion_your_name_spoilers/dfysl4l/",
    postId: "t3_63yjc7",
    parentId: "t3_63yjc7",
    username: "ATonOfBacon",
    userId: "t2_92ta3",
    category: "movies",
    communityName: "r/movies",
    body: 'That was by far one of the best endings I\'ve seen. A lot of people want the whole, "What happened afterwards? Kids? Family? Work?"\n\nFor me, it was great just to keep it to where they finally get to meet each other face to face in a setting where they will not be taken away from each other and nothing stands in their way. For the viewer, we pretty much can interpret their lives afterwards based on what we want, which is nice. Throughout the entire movie, all we wanted was them to just meet each other. No kiss. No embrace. Just the moment where they can be in the presence of each other without being torn apart.\n\nAnd the music? I just went and ordered the OST online. Worth it! \n\nI will watch this again very soon.',
    createdAt: "2017-04-07T18:23:32.000Z",
    scrapedAt: "2024-10-13T19:31:20.672Z",
    upVotes: 545,
    numberOfreplies: 6,
    html: '&lt;div class="md"&gt;&lt;p&gt;That was by far one of the best endings I&amp;#39;ve seen. A lot of people want the whole, &amp;quot;What happened afterwards? Kids? Family? Work?&amp;quot;&lt;/p&gt;\n\n&lt;p&gt;For me, it was great just to keep it to where they finally get to meet each other face to face in a setting where they will not be taken away from each other and nothing stands in their way. For the viewer, we pretty much can interpret their lives afterwards based on what we want, which is nice. Throughout the entire movie, all we wanted was them to just meet each other. No kiss. No embrace. Just the moment where they can be in the presence of each other without being torn apart.&lt;/p&gt;\n\n&lt;p&gt;And the music? I just went and ordered the OST online. Worth it! &lt;/p&gt;\n\n&lt;p&gt;I will watch this again very soon.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_dfyv4n9",
    parsedId: "dfyv4n9",
    url: "https://www.reddit.com/r/movies/comments/63yjc7/official_discussion_your_name_spoilers/dfyv4n9/",
    postId: "t3_63yjc7",
    parentId: "t1_dfysl4l",
    username: "Aviri",
    userId: "t2_8qjxx",
    category: "movies",
    communityName: "r/movies",
    body: "Spotify has the whole album if you haven't seen it already.",
    createdAt: "2017-04-07T19:10:22.000Z",
    scrapedAt: "2024-10-13T19:31:20.672Z",
    upVotes: 93,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;Spotify has the whole album if you haven&amp;#39;t seen it already.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_dg09cz8",
    parsedId: "dg09cz8",
    url: "https://www.reddit.com/r/movies/comments/63yjc7/official_discussion_your_name_spoilers/dg09cz8/",
    postId: "t3_63yjc7",
    parentId: "t1_dfysl4l",
    username: "Pegguins",
    userId: "t2_h94m7",
    category: "movies",
    communityName: "r/movies",
    body: "The ending is brilliant though. Shinkai weaves narrative and message I to the plot and visuals of his films in a phenomenal way. You're supposed to go away and think about what happens next, to take you're own take on the future and message he was getting at. Spelling it out would greatly reduce the power of the ending.",
    createdAt: "2017-04-08T19:36:52.000Z",
    scrapedAt: "2024-10-13T19:31:20.672Z",
    upVotes: 83,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;The ending is brilliant though. Shinkai weaves narrative and message I to the plot and visuals of his films in a phenomenal way. You&amp;#39;re supposed to go away and think about what happens next, to take you&amp;#39;re own take on the future and message he was getting at. Spelling it out would greatly reduce the power of the ending.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_dg09acf",
    parsedId: "dg09acf",
    url: "https://www.reddit.com/r/movies/comments/63yjc7/official_discussion_your_name_spoilers/dg09acf/",
    postId: "t3_63yjc7",
    parentId: "t1_dfysl4l",
    username: "[deleted]",
    category: "movies",
    communityName: "r/movies",
    body: "I'm sure any watcher of the director's previous works was extremely satisfied with the leads simply meeting each other alone.",
    createdAt: "2017-04-08T19:35:07.000Z",
    scrapedAt: "2024-10-13T19:31:20.672Z",
    upVotes: 35,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;I&amp;#39;m sure any watcher of the director&amp;#39;s previous works was extremely satisfied with the leads simply meeting each other alone.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_dg0xot4",
    parsedId: "dg0xot4",
    url: "https://www.reddit.com/r/movies/comments/63yjc7/official_discussion_your_name_spoilers/dg0xot4/",
    postId: "t3_63yjc7",
    parentId: "t1_dfysl4l",
    username: "sleepycharlie",
    userId: "t2_blug5",
    category: "movies",
    communityName: "r/movies",
    body: "Anyone who wanted more from the ending completely missed the point of the movie. Plus, I love movies that don't go into all of that stuff because it's incredibly unnecessary. Similarly to what happened during the magic hour, there was no need for kissing or hugging. There was emotion, and we don't need things like physical affection to understand that. Their words and expressions did enough of it.",
    createdAt: "2017-04-09T06:31:04.000Z",
    scrapedAt: "2024-10-13T19:31:20.672Z",
    upVotes: 26,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;Anyone who wanted more from the ending completely missed the point of the movie. Plus, I love movies that don&amp;#39;t go into all of that stuff because it&amp;#39;s incredibly unnecessary. Similarly to what happened during the magic hour, there was no need for kissing or hugging. There was emotion, and we don&amp;#39;t need things like physical affection to understand that. Their words and expressions did enough of it.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_1b268iq",
    parsedId: "1b268iq",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/1b268iq/makoto_shinkai_speaks_on_your_name_producer/",
    username: "Oatmeel97",
    userId: "t2_cptm37k6",
    title:
      "Makoto Shinkai Speaks On Your Name Producer Kouichirou Itou’s Arrest",
    communityName: "r/KimiNoNaWa",
    parsedCommunityName: "KimiNoNaWa",
    body: "URL: https://www.animeexplained.com/news/your-name-director-makoto-shinkai-speaks-on-producer-kouichirou-itous-arrest/\nThumbnail: https://b.thumbs.redditmedia.com/TF7wLqNaoM-_urMCfbxjJD2TiVmsvh63Lri32_GahrE.jpg\nImages:\n\thttps://external-preview.redd.it/flK6ArnJHryBlrXUmbgPUSpPp4PTuSi20rf6o3ULfcY.jpg?auto=webp&amp;s=ff1eeb1657fc7b69aa22032c807fab8316b58efe\n",
    html: null,
    numberOfComments: 17,
    flair: "News",
    upVotes: 151,
    upVoteRatio: 1,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl:
      "https://b.thumbs.redditmedia.com/TF7wLqNaoM-_urMCfbxjJD2TiVmsvh63Lri32_GahrE.jpg",
    createdAt: "2024-02-28T13:36:55.000Z",
    scrapedAt: "2024-10-13T19:31:23.401Z",
    dataType: "post",
  },
  {
    id: "t1_ksjm172",
    parsedId: "ksjm172",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/1b268iq/makoto_shinkai_speaks_on_your_name_producer/ksjm172/",
    postId: "t3_1b268iq",
    parentId: "t3_1b268iq",
    username: "alatreph",
    userId: "t2_petx1ofu",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "A good response. Something like this coming out about a producer on the film? I agree with Shinkai, it doesn't diminish the value of the film. An artist or writer, though? I'd start to have second thoughts. But different people will draw that line at different places, and it's good that he acknowledges that.",
    createdAt: "2024-02-28T15:15:16.000Z",
    scrapedAt: "2024-10-13T19:31:23.499Z",
    upVotes: 98,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;A good response. Something like this coming out about a producer on the film? I agree with Shinkai, it doesn&amp;#39;t diminish the value of the film. An artist or writer, though? I&amp;#39;d start to have second thoughts. But different people will draw that line at different places, and it&amp;#39;s good that he acknowledges that.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_ksphe0x",
    parsedId: "ksphe0x",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/1b268iq/makoto_shinkai_speaks_on_your_name_producer/ksphe0x/",
    postId: "t3_1b268iq",
    parentId: "t1_ksjm172",
    username: "Barnard87",
    userId: "t2_x864w",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "I'm a firm believer that shitty people can still make great things, and it's importance to distinguish and separate the two.  \n\nNow, if that work of art is inspired by said shitty person's experiences? Definitely can detract from and even make the work itself bad.  \n\nBut if someone makes a great story, then gets arrested for say, murder, and that isn't maliciously linked in their writing or drawing, id comprehend it as a great piece of work by a shitty human.  \n\nAs you said though, it's up to everyone on where to draw that line.",
    createdAt: "2024-02-29T15:39:43.000Z",
    scrapedAt: "2024-10-13T19:31:23.499Z",
    upVotes: 10,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;I&amp;#39;m a firm believer that shitty people can still make great things, and it&amp;#39;s importance to distinguish and separate the two.  &lt;/p&gt;\n\n&lt;p&gt;Now, if that work of art is inspired by said shitty person&amp;#39;s experiences? Definitely can detract from and even make the work itself bad.  &lt;/p&gt;\n\n&lt;p&gt;But if someone makes a great story, then gets arrested for say, murder, and that isn&amp;#39;t maliciously linked in their writing or drawing, id comprehend it as a great piece of work by a shitty human.  &lt;/p&gt;\n\n&lt;p&gt;As you said though, it&amp;#39;s up to everyone on where to draw that line.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_kstk744",
    parsedId: "kstk744",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/1b268iq/makoto_shinkai_speaks_on_your_name_producer/kstk744/",
    postId: "t3_1b268iq",
    parentId: "t3_1b268iq",
    username: "Timely_Street_3075",
    userId: "t2_jfha54k6l",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "The fact that Harvey Weinstein is associated with movies like Pulp Fiction, Good Will Hunting, Kill Bill, LOTR, Princess Mononoke, The King's Speech, Inglorious Bastards, and many more gems doesn't diminish the movies. It just shows how shrewd the man was in selecting movies that would profit him and increase his hold on Hollywood. He was a businessman who knew where to invest his money. He used that money for wrong. But that doesn't diminish the projects he invested in.",
    createdAt: "2024-03-01T07:11:58.000Z",
    scrapedAt: "2024-10-13T19:31:23.499Z",
    upVotes: 8,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;The fact that Harvey Weinstein is associated with movies like Pulp Fiction, Good Will Hunting, Kill Bill, LOTR, Princess Mononoke, The King&amp;#39;s Speech, Inglorious Bastards, and many more gems doesn&amp;#39;t diminish the movies. It just shows how shrewd the man was in selecting movies that would profit him and increase his hold on Hollywood. He was a businessman who knew where to invest his money. He used that money for wrong. But that doesn&amp;#39;t diminish the projects he invested in.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_ksou2bm",
    parsedId: "ksou2bm",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/1b268iq/makoto_shinkai_speaks_on_your_name_producer/ksou2bm/",
    postId: "t3_1b268iq",
    parentId: "t3_1b268iq",
    username: "SS-PL",
    userId: "t2_fbzfo87i",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "Itou probably got inspired after seeing Shinkai’s The Garden of Words",
    createdAt: "2024-02-29T13:08:36.000Z",
    scrapedAt: "2024-10-13T19:31:23.499Z",
    upVotes: 7,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;Itou probably got inspired after seeing Shinkai’s The Garden of Words&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_ksl98xz",
    parsedId: "ksl98xz",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/1b268iq/makoto_shinkai_speaks_on_your_name_producer/ksl98xz/",
    postId: "t3_1b268iq",
    parentId: "t3_1b268iq",
    username: "Matichado",
    userId: "t2_8nfosmhy",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "This news hurt me and my system a lot, Kimi No Na wa has been my favorite movie since late 2020 so much so that as a result of my DID (dissociative identidy disorder) I gained two introjects (alters based on fictional characters) based on Taki and Mitsuha, they also were really hurt by this, Mitsuha rn is not feeling very well about it particularly. We apologize that we are writing this here but we haven’t had the chance to properly drain this",
    createdAt: "2024-02-28T20:36:20.000Z",
    scrapedAt: "2024-10-13T19:31:23.499Z",
    upVotes: -39,
    numberOfreplies: 4,
    html: '&lt;div class="md"&gt;&lt;p&gt;This news hurt me and my system a lot, Kimi No Na wa has been my favorite movie since late 2020 so much so that as a result of my DID (dissociative identidy disorder) I gained two introjects (alters based on fictional characters) based on Taki and Mitsuha, they also were really hurt by this, Mitsuha rn is not feeling very well about it particularly. We apologize that we are writing this here but we haven’t had the chance to properly drain this&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_t1s1vs",
    parsedId: "t1s1vs",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/t1s1vs/what_happens_after_the_end_of_your_name/",
    username: "Aggravating_Bend_112",
    userId: "t2_7fyslsrk",
    title: "What happens after the end of Your Name?",
    communityName: "r/KimiNoNaWa",
    parsedCommunityName: "KimiNoNaWa",
    body: "I finally got around to watching this movie, and it's probably the best anime movie i've ever seen. (9.5/10).\n\nHowever, the ending keeps bugging me. Is there a canon confirmation about what happened after their reunion? If not, what is the popular fan theory?",
    html: '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;I finally got around to watching this movie, and it&amp;#39;s probably the best anime movie i&amp;#39;ve ever seen. (9.5/10).&lt;/p&gt;\n\n&lt;p&gt;However, the ending keeps bugging me. Is there a canon confirmation about what happened after their reunion? If not, what is the popular fan theory?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
    numberOfComments: 17,
    flair: "Discussion",
    upVotes: 32,
    upVoteRatio: 0.9,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl: "self",
    createdAt: "2022-02-26T08:21:40.000Z",
    scrapedAt: "2024-10-13T19:31:25.208Z",
    dataType: "post",
  },
  {
    id: "t1_hyidvha",
    parsedId: "hyidvha",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/t1s1vs/what_happens_after_the_end_of_your_name/hyidvha/",
    postId: "t3_t1s1vs",
    parentId: "t3_t1s1vs",
    username: "KralizecCL",
    userId: "t2_h0dokvwi",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: 'The only canon source I am aware of is Makoto Shinkai\'s "Weathering with you" (WWY). In that movie, both Taki and Mitsuha made cameos, but they are not shown together explicitly... but in the WWY light novel (that I\'ve not read yet) it is said that inside Taki\'s grandmother house it is described a picture of Taki and Mitsuha\'s wedding, supposedly from 2024. And I understand Makoto Shinkai himself had never said what he had in mind about it besides of that.\n\nSo, TL;DR; they finish together married.\n\nBut: do they recover their memory? Nobody officially knows (worse about how they actually did it, if they did); or did they felt only felt that strong mysterious connection that lead them to fall in love (again) without ever remembering their real past?  Nobody knows...\n\nBecause of that, there is ample of fanfics that looks for an answer about what\'s next, exploring all the map. Ones where they remember each other at glance and start dating; others where they feel they know and manage to recover (partially or totally) their memory later; and others where they never actually recover their memories, but their bonds leads them to fall in love anyway. All of them with plenty of adventures around their dating and the interaction with their friends and family. But I\'d say all of them manage to make them be finally together as that is, at the end, canon, and not doing so would be, err, cruel?\n\nAnd, I am one who wrote one of those fanfics, if you want to continue the story exactly from the last scene at the Suga Shrine stairs. You can read my fanfic ["Rediscovering the Future"](https://www.fanfiction.net/s/14032763/1/Rediscovering-the-Future) (FFN); in FFN you can also a lot of other fanfics quite interesting and lovely written. I like in particular these three (so far): ["Kimi no Na wa: Future"](https://www.fanfiction.net/s/12355349/1/Kimi-no-Na-wa-Future) by  Alyena2x, "[Remembering You](https://www.fanfiction.net/s/12390474/1/Remembering-You)" by Shining Arrows and "[Reception](https://www.fanfiction.net/s/13754932/1/Reception)" by Brishna. In AO3 I understand there are a bunch more, but I haven\'t go there yet. Maybe others can recommend some good ones from there.',
    createdAt: "2022-02-26T13:09:08.000Z",
    scrapedAt: "2024-10-13T19:31:25.307Z",
    upVotes: 13,
    numberOfreplies: 2,
    html: '&lt;div class="md"&gt;&lt;p&gt;The only canon source I am aware of is Makoto Shinkai&amp;#39;s &amp;quot;Weathering with you&amp;quot; (WWY). In that movie, both Taki and Mitsuha made cameos, but they are not shown together explicitly... but in the WWY light novel (that I&amp;#39;ve not read yet) it is said that inside Taki&amp;#39;s grandmother house it is described a picture of Taki and Mitsuha&amp;#39;s wedding, supposedly from 2024. And I understand Makoto Shinkai himself had never said what he had in mind about it besides of that.&lt;/p&gt;\n\n&lt;p&gt;So, TL;DR; they finish together married.&lt;/p&gt;\n\n&lt;p&gt;But: do they recover their memory? Nobody officially knows (worse about how they actually did it, if they did); or did they felt only felt that strong mysterious connection that lead them to fall in love (again) without ever remembering their real past?  Nobody knows...&lt;/p&gt;\n\n&lt;p&gt;Because of that, there is ample of fanfics that looks for an answer about what&amp;#39;s next, exploring all the map. Ones where they remember each other at glance and start dating; others where they feel they know and manage to recover (partially or totally) their memory later; and others where they never actually recover their memories, but their bonds leads them to fall in love anyway. All of them with plenty of adventures around their dating and the interaction with their friends and family. But I&amp;#39;d say all of them manage to make them be finally together as that is, at the end, canon, and not doing so would be, err, cruel?&lt;/p&gt;\n\n&lt;p&gt;And, I am one who wrote one of those fanfics, if you want to continue the story exactly from the last scene at the Suga Shrine stairs. You can read my fanfic &lt;a href="https://www.fanfiction.net/s/14032763/1/Rediscovering-the-Future"&gt;&amp;quot;Rediscovering the Future&amp;quot;&lt;/a&gt; (FFN); in FFN you can also a lot of other fanfics quite interesting and lovely written. I like in particular these three (so far): &lt;a href="https://www.fanfiction.net/s/12355349/1/Kimi-no-Na-wa-Future"&gt;&amp;quot;Kimi no Na wa: Future&amp;quot;&lt;/a&gt; by  Alyena2x, &amp;quot;&lt;a href="https://www.fanfiction.net/s/12390474/1/Remembering-You"&gt;Remembering You&lt;/a&gt;&amp;quot; by Shining Arrows and &amp;quot;&lt;a href="https://www.fanfiction.net/s/13754932/1/Reception"&gt;Reception&lt;/a&gt;&amp;quot; by Brishna. In AO3 I understand there are a bunch more, but I haven&amp;#39;t go there yet. Maybe others can recommend some good ones from there.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_jn1xsin",
    parsedId: "jn1xsin",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/t1s1vs/what_happens_after_the_end_of_your_name/jn1xsin/",
    postId: "t3_t1s1vs",
    parentId: "t1_hyidvha",
    username: "AnasurimborKellhus",
    userId: "t2_jb7s3",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "C'mon dude, it's 2 am here now, why did you make me start reading it right after I watched the movie, I want to sleep!",
    createdAt: "2023-06-05T23:34:35.000Z",
    scrapedAt: "2024-10-13T19:31:25.307Z",
    upVotes: 2,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;C&amp;#39;mon dude, it&amp;#39;s 2 am here now, why did you make me start reading it right after I watched the movie, I want to sleep!&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_b8cr9o",
    parsedId: "b8cr9o",
    url: "https://www.reddit.com/r/movies/comments/b8cr9o/the_masterpiece_that_was_your_name/",
    username: "ODMAN03",
    userId: "t2_16pj5i",
    title: "The masterpiece that was 'Your Name'",
    communityName: "r/movies",
    parsedCommunityName: "movies",
    body: "“Nothing more... nothing less... than a beautiful view.”\n\nAround the 20th of April last year, I watched ‘Your Name’. It was a movie I had heard all about. One of the critics I followed loved it (Chris Stuckmann) and it was talked about all around the community. I knew I had to watch it. But since it wasn’t in cinemas when I wanted to watch it, I had to buy a DVD (I didn’t have and still don’t have a blu-ray. Plan on buying a blu-ray player and ‘Your Name’ again). There was a lot of build up to watching this movie, since it took a little while for the movie to actually get to my house. But then on that day, on the 20th of April, I finally watched it.\n\nI don’t think I can explain my experience through words. There was something about this movie that just clicked with me. Whether it was the characters or the story, something about it just… did something to me…\n\n‘Your Name’ follows Taki and Mitsuha, two high school students who live on two very different parts of Japan, one being in the middle of Tokyo and one being in the country. One day, the two strangers switch bodies with each other. With Taki in Mitsuha’s body, and Mitsuha in Taki’s. We get to see how Taki and Mitsuha have to change their lives for each other. We see them grow and change through this body switch.\n\nI am a person who likes to have everything in a movie to be as great as possible. I want the characters to be good, I want the story to be good, I want the visuals to be good. I want everything in a movie or show to be good. Now, this has lead to me thinking more about movies with my head rather than the heart. It has lead to me rating a movie/show lower cause I realized that the characters weren’t that memorable. It has led to me not feeling anything, cause I was just thinking.\n\nIf I look back at this film, it never feels as good as it does when you watch it. I look at the characters, and the story, and the music separately which leads me to slowly dislike the film. It’s not that I realize things about the aspects that make it worse, but just some weird feeling that it isn’t as good as I thought.\n\nBut when I watch this film, there is just something that happens. I’m completely engrossed by its story and characters, that it is hard to see some of the mistakes. Cause there are mistakes and flaws in this film for sure.\n\nThe characters could’ve had a little more depth, the story had some holes and the third act felt a little slower than the rest.\n\nBut whenever I actually watch the film, all of those flaws disappear in my head. The characters feel real and I’m invested in the story. I don’t think I can explain through text how much I love this movie. But I’ll try.\n\nMy favorite part of ‘Your name’ is how its story and characters have a connection. It doesn’t feel as if they wrote a story, and then wrote characters. They never felt separated but were completely connected. That the characters develop through this body change that occurs multiple times under the film. That Mitsuha and Taki learn about their desired lifestyle. How Mitsuha learns how stressful the life in the city is or how Taki learns about culture and connection in the country (it is never stated that Taki dislikes his life in the city, but it was something I wanted to add since Mitsuha shows the stress that is in the city). That Taki doesn’t do anything with his life until Mitsuha changes that, and how he repays her by saving her life.\n\nOr how the story has themes of what the Japanese society is becoming. That they are drifting away from culture (religion) and into modernization and politics. About wanting to keep a balance between culture and modernization. A whether you should uphold tradition, or be yourself.\n\nAnd how all of that being connected with the dreams that the main cast experience, of how they get to see how their wished lives would’ve been. They get to see whether or not it is their culture or their dreams they want to take force in their future. Whether they want to continue to live the life they have lived all of their lives, or if they want to make a risk and maybe feel a little uncomfortable but in the end live a better life.\n\nIn the end, I think the characters and story both embody the constant struggle between the two sides.\n\nBut then there’s also the constant feeling of looking for something that might fulfill themselves that is referenced. Whether it is a person, a place, or even just a job.\n\nThere are a lot of movies and shows that have a character or a plot element that I find relatable. But this the first time I felt the same about a feeling expressed in a medium. Maybe I explained it badly. The feeling of trying to find something that might fulfill yourself is something I think everyone has felt. Or maybe not even fulfill, but just trying to find something, cause you have the constant feeling that you need to find it.\n\nI can’t believe I have gone through this review this long without mentioning the art.\n\nThere are a lot of shows and movies I would consider visual masterpieces. Like ‘Spiderman into the spiderverse’, ‘A Silent Voice’ or Ridley Scott’s ‘Alien’. And while I would still consider them a few of the most visually appealing movies of all time, there is something about ‘Your name\\* that makes it so beautiful. Whether it is the incredibly detailed backgrounds that fit so incredibly well with the fantastic, or if it’s the coloring that brings the emotion so well together with its shading. It is a mystery I have yet to solve, but want to keep a secret. To have something to have unexplained.\n\nAnd I can’t not bring up the music. Wow, what an amazing score. The work by ‘Radwimps’ is honestly something I admire completely. It is one of the few soundtracks that I almost remember completely. It is what makes many of the scenes into what they really are. It’s what makes so many of the scenes bone-chilling. It’s what makes so many of the scenes so marveling.\n\nAt the end of the day, I absolutely love ‘Your Name’. It is a movie that I think I will have in my mind for all of my life. A movie whose score will be stuck in my head for eternity. A movie who’s visuals will be ingrained in my brain. And a story of which will be cemented into my soul.\n\nI have seen movies that I think are as good as Your name. 2001 a space odyssey, a clockwork orange are both two movies I think are about as good as this film. But in those two, it is more the thought-provoking and complicated story that they have. They aren’t necessarily movies that are made for the heart, but are still amazing for it. But when I watch ‘Your Name’, something about it just grabs me. I don’t know what it is, but the first time I watched it, I loved it completely. But I don’t know how to describe it. It isn’t a sad film, not necessarily a realistic one nor a romantic one. You could probably describe in many ways. but for me - it is the unnamable. Nothing more, nothing less, than a beautiful film\n\n[https://letterboxd.com/artistwithaname/film/your-name/2/](https://letterboxd.com/artistwithaname/film/your-name/2/)\n\nEdit: I’m honestly so glad I made this (these) posts. Whether it is negative or positive, I’m just glad that people are talking about Your Name again. I never really wanted to do a review of it, but I’m glad I did!\n\nEdit 2: And last thing. I can go on and on about why I love this film. I can analyze every aspect of it. But the fact of the matter is that there is just one thing that makes me love it so much. Cause it makes me happy. I haven’t really felt that good for the past years. I’m not sad, not happy, I just feel an emptiness where my feeling should be. But whenever I watch this film or listen to it’s score, I’m happy. Or at least I think I am. I can feel a warmth inside of myself when I watch it, and I think that’s it. It has problems, but it makes me happy every time I watch it. And therefore, it is one of the best movies I have seen",
    html: '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;“Nothing more... nothing less... than a beautiful view.”&lt;/p&gt;\n\n&lt;p&gt;Around the 20th of April last year, I watched ‘Your Name’. It was a movie I had heard all about. One of the critics I followed loved it (Chris Stuckmann) and it was talked about all around the community. I knew I had to watch it. But since it wasn’t in cinemas when I wanted to watch it, I had to buy a DVD (I didn’t have and still don’t have a blu-ray. Plan on buying a blu-ray player and ‘Your Name’ again). There was a lot of build up to watching this movie, since it took a little while for the movie to actually get to my house. But then on that day, on the 20th of April, I finally watched it.&lt;/p&gt;\n\n&lt;p&gt;I don’t think I can explain my experience through words. There was something about this movie that just clicked with me. Whether it was the characters or the story, something about it just… did something to me…&lt;/p&gt;\n\n&lt;p&gt;‘Your Name’ follows Taki and Mitsuha, two high school students who live on two very different parts of Japan, one being in the middle of Tokyo and one being in the country. One day, the two strangers switch bodies with each other. With Taki in Mitsuha’s body, and Mitsuha in Taki’s. We get to see how Taki and Mitsuha have to change their lives for each other. We see them grow and change through this body switch.&lt;/p&gt;\n\n&lt;p&gt;I am a person who likes to have everything in a movie to be as great as possible. I want the characters to be good, I want the story to be good, I want the visuals to be good. I want everything in a movie or show to be good. Now, this has lead to me thinking more about movies with my head rather than the heart. It has lead to me rating a movie/show lower cause I realized that the characters weren’t that memorable. It has led to me not feeling anything, cause I was just thinking.&lt;/p&gt;\n\n&lt;p&gt;If I look back at this film, it never feels as good as it does when you watch it. I look at the characters, and the story, and the music separately which leads me to slowly dislike the film. It’s not that I realize things about the aspects that make it worse, but just some weird feeling that it isn’t as good as I thought.&lt;/p&gt;\n\n&lt;p&gt;But when I watch this film, there is just something that happens. I’m completely engrossed by its story and characters, that it is hard to see some of the mistakes. Cause there are mistakes and flaws in this film for sure.&lt;/p&gt;\n\n&lt;p&gt;The characters could’ve had a little more depth, the story had some holes and the third act felt a little slower than the rest.&lt;/p&gt;\n\n&lt;p&gt;But whenever I actually watch the film, all of those flaws disappear in my head. The characters feel real and I’m invested in the story. I don’t think I can explain through text how much I love this movie. But I’ll try.&lt;/p&gt;\n\n&lt;p&gt;My favorite part of ‘Your name’ is how its story and characters have a connection. It doesn’t feel as if they wrote a story, and then wrote characters. They never felt separated but were completely connected. That the characters develop through this body change that occurs multiple times under the film. That Mitsuha and Taki learn about their desired lifestyle. How Mitsuha learns how stressful the life in the city is or how Taki learns about culture and connection in the country (it is never stated that Taki dislikes his life in the city, but it was something I wanted to add since Mitsuha shows the stress that is in the city). That Taki doesn’t do anything with his life until Mitsuha changes that, and how he repays her by saving her life.&lt;/p&gt;\n\n&lt;p&gt;Or how the story has themes of what the Japanese society is becoming. That they are drifting away from culture (religion) and into modernization and politics. About wanting to keep a balance between culture and modernization. A whether you should uphold tradition, or be yourself.&lt;/p&gt;\n\n&lt;p&gt;And how all of that being connected with the dreams that the main cast experience, of how they get to see how their wished lives would’ve been. They get to see whether or not it is their culture or their dreams they want to take force in their future. Whether they want to continue to live the life they have lived all of their lives, or if they want to make a risk and maybe feel a little uncomfortable but in the end live a better life.&lt;/p&gt;\n\n&lt;p&gt;In the end, I think the characters and story both embody the constant struggle between the two sides.&lt;/p&gt;\n\n&lt;p&gt;But then there’s also the constant feeling of looking for something that might fulfill themselves that is referenced. Whether it is a person, a place, or even just a job.&lt;/p&gt;\n\n&lt;p&gt;There are a lot of movies and shows that have a character or a plot element that I find relatable. But this the first time I felt the same about a feeling expressed in a medium. Maybe I explained it badly. The feeling of trying to find something that might fulfill yourself is something I think everyone has felt. Or maybe not even fulfill, but just trying to find something, cause you have the constant feeling that you need to find it.&lt;/p&gt;\n\n&lt;p&gt;I can’t believe I have gone through this review this long without mentioning the art.&lt;/p&gt;\n\n&lt;p&gt;There are a lot of shows and movies I would consider visual masterpieces. Like ‘Spiderman into the spiderverse’, ‘A Silent Voice’ or Ridley Scott’s ‘Alien’. And while I would still consider them a few of the most visually appealing movies of all time, there is something about ‘Your name* that makes it so beautiful. Whether it is the incredibly detailed backgrounds that fit so incredibly well with the fantastic, or if it’s the coloring that brings the emotion so well together with its shading. It is a mystery I have yet to solve, but want to keep a secret. To have something to have unexplained.&lt;/p&gt;\n\n&lt;p&gt;And I can’t not bring up the music. Wow, what an amazing score. The work by ‘Radwimps’ is honestly something I admire completely. It is one of the few soundtracks that I almost remember completely. It is what makes many of the scenes into what they really are. It’s what makes so many of the scenes bone-chilling. It’s what makes so many of the scenes so marveling.&lt;/p&gt;\n\n&lt;p&gt;At the end of the day, I absolutely love ‘Your Name’. It is a movie that I think I will have in my mind for all of my life. A movie whose score will be stuck in my head for eternity. A movie who’s visuals will be ingrained in my brain. And a story of which will be cemented into my soul.&lt;/p&gt;\n\n&lt;p&gt;I have seen movies that I think are as good as Your name. 2001 a space odyssey, a clockwork orange are both two movies I think are about as good as this film. But in those two, it is more the thought-provoking and complicated story that they have. They aren’t necessarily movies that are made for the heart, but are still amazing for it. But when I watch ‘Your Name’, something about it just grabs me. I don’t know what it is, but the first time I watched it, I loved it completely. But I don’t know how to describe it. It isn’t a sad film, not necessarily a realistic one nor a romantic one. You could probably describe in many ways. but for me - it is the unnamable. Nothing more, nothing less, than a beautiful film&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://letterboxd.com/artistwithaname/film/your-name/2/"&gt;https://letterboxd.com/artistwithaname/film/your-name/2/&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;Edit: I’m honestly so glad I made this (these) posts. Whether it is negative or positive, I’m just glad that people are talking about Your Name again. I never really wanted to do a review of it, but I’m glad I did!&lt;/p&gt;\n\n&lt;p&gt;Edit 2: And last thing. I can go on and on about why I love this film. I can analyze every aspect of it. But the fact of the matter is that there is just one thing that makes me love it so much. Cause it makes me happy. I haven’t really felt that good for the past years. I’m not sad, not happy, I just feel an emptiness where my feeling should be. But whenever I watch this film or listen to it’s score, I’m happy. Or at least I think I am. I can feel a warmth inside of myself when I watch it, and I think that’s it. It has problems, but it makes me happy every time I watch it. And therefore, it is one of the best movies I have seen&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
    numberOfComments: 172,
    flair: "Review",
    upVotes: 553,
    upVoteRatio: 0.84,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl: "spoiler",
    createdAt: "2019-04-02T01:44:12.000Z",
    scrapedAt: "2024-10-13T19:31:25.410Z",
    dataType: "post",
  },
  {
    id: "t1_jn20jyp",
    parsedId: "jn20jyp",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/t1s1vs/what_happens_after_the_end_of_your_name/jn20jyp/",
    postId: "t3_t1s1vs",
    parentId: "t1_jn1xsin",
    username: "KralizecCL",
    userId: "t2_h0dokvwi",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "O-k. Better you go to sleep right now first.... if you can sleep without continue thinking about the movie :-P.\n\nBut, after you sleep, give it a try! :-D",
    createdAt: "2023-06-05T23:55:25.000Z",
    scrapedAt: "2024-10-13T19:31:25.307Z",
    upVotes: 1,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;O-k. Better you go to sleep right now first.... if you can sleep without continue thinking about the movie :-P.&lt;/p&gt;\n\n&lt;p&gt;But, after you sleep, give it a try! :-D&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_ejx6xv2",
    parsedId: "ejx6xv2",
    url: "https://www.reddit.com/r/movies/comments/b8cr9o/the_masterpiece_that_was_your_name/ejx6xv2/",
    postId: "t3_b8cr9o",
    parentId: "t3_b8cr9o",
    username: "The_Auchtor",
    userId: "t2_835o9",
    category: "movies",
    communityName: "r/movies",
    body: "Just watched this again yesterday. Almost every scene could be a desktop image. The movie brought me to tears.",
    createdAt: "2019-04-02T02:33:55.000Z",
    scrapedAt: "2024-10-13T19:31:25.492Z",
    upVotes: 183,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;Just watched this again yesterday. Almost every scene could be a desktop image. The movie brought me to tears.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_l1omz3h",
    parsedId: "l1omz3h",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/t1s1vs/what_happens_after_the_end_of_your_name/l1omz3h/",
    postId: "t3_t1s1vs",
    parentId: "t1_jn20jyp",
    username: "toastercook",
    userId: "t2_pipsh8k",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "It is also 3:38 in the morning on a Monday for me :(",
    createdAt: "2024-04-28T19:39:09.000Z",
    scrapedAt: "2024-10-13T19:31:25.307Z",
    upVotes: 2,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;It is also 3:38 in the morning on a Monday for me :(&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_ejx7iq7",
    parsedId: "ejx7iq7",
    url: "https://www.reddit.com/r/movies/comments/b8cr9o/the_masterpiece_that_was_your_name/ejx7iq7/",
    postId: "t3_b8cr9o",
    parentId: "t1_ejx6xv2",
    username: "BIG_PY",
    userId: "t2_3yqw2",
    category: "movies",
    communityName: "r/movies",
    body: "That's Makoto Shinkai for ya.",
    createdAt: "2019-04-02T02:41:51.000Z",
    scrapedAt: "2024-10-13T19:31:25.492Z",
    upVotes: 47,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;That&amp;#39;s Makoto Shinkai for ya.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_l1s2zd3",
    parsedId: "l1s2zd3",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/t1s1vs/what_happens_after_the_end_of_your_name/l1s2zd3/",
    postId: "t3_t1s1vs",
    parentId: "t1_l1omz3h",
    username: "KralizecCL",
    userId: "t2_h0dokvwi",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "Always is a good time to go deeper into the KNNW universe :-)",
    createdAt: "2024-04-29T12:55:06.000Z",
    scrapedAt: "2024-10-13T19:31:25.307Z",
    upVotes: 1,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;Always is a good time to go deeper into the KNNW universe :-)&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_ejxm3yc",
    parsedId: "ejxm3yc",
    url: "https://www.reddit.com/r/movies/comments/b8cr9o/the_masterpiece_that_was_your_name/ejxm3yc/",
    postId: "t3_b8cr9o",
    parentId: "t1_ejx7iq7",
    username: "Richard_Bastion",
    userId: "t2_afo65",
    category: "movies",
    communityName: "r/movies",
    body: "50 Wallpapers A Second",
    createdAt: "2019-04-02T07:27:16.000Z",
    scrapedAt: "2024-10-13T19:31:25.492Z",
    upVotes: 71,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;50 Wallpapers A Second&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_ku9nm3m",
    parsedId: "ku9nm3m",
    url: "https://www.reddit.com/r/movies/comments/b8cr9o/the_masterpiece_that_was_your_name/ku9nm3m/",
    postId: "t3_b8cr9o",
    parentId: "t1_ejxm3yc",
    username: "kordon_blurr48",
    userId: "t2_t0r3p4bo",
    category: "movies",
    communityName: "r/movies",
    body: "😂",
    createdAt: "2024-03-10T20:20:26.000Z",
    scrapedAt: "2024-10-13T19:31:25.492Z",
    upVotes: 1,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;😂&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_ejx4qkb",
    parsedId: "ejx4qkb",
    url: "https://www.reddit.com/r/movies/comments/b8cr9o/the_masterpiece_that_was_your_name/ejx4qkb/",
    postId: "t3_b8cr9o",
    parentId: "t3_b8cr9o",
    username: "ienjoymen",
    userId: "t2_79rnw",
    category: "movies",
    communityName: "r/movies",
    body: "One of the best movies I've seen in recent years",
    createdAt: "2019-04-02T02:05:09.000Z",
    scrapedAt: "2024-10-13T19:31:25.492Z",
    upVotes: 112,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;One of the best movies I&amp;#39;ve seen in recent years&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_1503ezn",
    parsedId: "1503ezn",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/1503ezn/what_was_the_messagetheme_of_your_name/",
    username: "EngineSensitive2584",
    userId: "t2_f2iwup5x",
    title: "What was the message/theme of Your Name?",
    communityName: "r/KimiNoNaWa",
    parsedCommunityName: "KimiNoNaWa",
    body: "I just finished watching Your Name., and, between this and Suzume Makoto Shinkai has officially taken up two spots on my list of favorite movies (just hoping Weathering With You is this good too). But despite how much I loved this movie I cannot understand what the message of it was.\n\nMy first thought is that it has something to do with connections and the passing of time, mostly due to the speeches Grandma gives about unions and how time is like threads, tangling, unraveling, and reconnecting, but other than that I'm completely lost. A lot of articles and video essays say that it's about truly understanding someone, I don't doubt that or think that whoever says that is wrong, but I don't think that that's all there is, I feel like there's something more to it than that\n\nI know this is something that's going to bother me if I just leave it alone and don't look into it, so would anyone be willing to explain this to an idiot like myself?",
    html: '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;I just finished watching Your Name., and, between this and Suzume Makoto Shinkai has officially taken up two spots on my list of favorite movies (just hoping Weathering With You is this good too). But despite how much I loved this movie I cannot understand what the message of it was.&lt;/p&gt;\n\n&lt;p&gt;My first thought is that it has something to do with connections and the passing of time, mostly due to the speeches Grandma gives about unions and how time is like threads, tangling, unraveling, and reconnecting, but other than that I&amp;#39;m completely lost. A lot of articles and video essays say that it&amp;#39;s about truly understanding someone, I don&amp;#39;t doubt that or think that whoever says that is wrong, but I don&amp;#39;t think that that&amp;#39;s all there is, I feel like there&amp;#39;s something more to it than that&lt;/p&gt;\n\n&lt;p&gt;I know this is something that&amp;#39;s going to bother me if I just leave it alone and don&amp;#39;t look into it, so would anyone be willing to explain this to an idiot like myself?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
    numberOfComments: 12,
    flair: "Discussion",
    upVotes: 27,
    upVoteRatio: 0.93,
    isVideo: false,
    isAd: false,
    over18: false,
    thumbnailUrl: "self",
    createdAt: "2023-07-15T05:48:22.000Z",
    scrapedAt: "2024-10-13T19:31:26.499Z",
    dataType: "post",
  },
  {
    id: "t1_js19ea3",
    parsedId: "js19ea3",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/1503ezn/what_was_the_messagetheme_of_your_name/js19ea3/",
    postId: "t3_1503ezn",
    parentId: "t3_1503ezn",
    username: "[deleted]",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "It's the red thread of fate. In asian myth, it is said the god Yue Lao ties a red thread or string to two people and they are destined to be together no matter how tangled or stretched the string gets. \n\nIn Your Name, the comet is going to fall no matter, the disaster is going to happen, the town will be destroyed. But Mitsuha can be saved so when she lives and the townsfolk are saved, the timeline corrects itself so her connection with Taki isn't necessary. But they are still tied by fate, so even though they can't remember it all, they are still drawn to each other. The grandmas speech is a reference to these threads.\n\nThat's how I understand it anyway.",
    createdAt: "2023-07-15T06:02:33.000Z",
    scrapedAt: "2024-10-13T19:31:26.588Z",
    upVotes: 23,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;It&amp;#39;s the red thread of fate. In asian myth, it is said the god Yue Lao ties a red thread or string to two people and they are destined to be together no matter how tangled or stretched the string gets. &lt;/p&gt;\n\n&lt;p&gt;In Your Name, the comet is going to fall no matter, the disaster is going to happen, the town will be destroyed. But Mitsuha can be saved so when she lives and the townsfolk are saved, the timeline corrects itself so her connection with Taki isn&amp;#39;t necessary. But they are still tied by fate, so even though they can&amp;#39;t remember it all, they are still drawn to each other. The grandmas speech is a reference to these threads.&lt;/p&gt;\n\n&lt;p&gt;That&amp;#39;s how I understand it anyway.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_js19k0n",
    parsedId: "js19k0n",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/1503ezn/what_was_the_messagetheme_of_your_name/js19k0n/",
    postId: "t3_1503ezn",
    parentId: "t3_1503ezn",
    username: "K242",
    userId: "t2_aij6l",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "What the message or theme of a movie is will vary from person to person; by nature, it is a fairly subjective topic. Personally, I like to think that the theme of Your Name is that the future is not predetermined; that fate is something you make for yourself.",
    createdAt: "2023-07-15T06:04:30.000Z",
    scrapedAt: "2024-10-13T19:31:26.588Z",
    upVotes: 9,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;What the message or theme of a movie is will vary from person to person; by nature, it is a fairly subjective topic. Personally, I like to think that the theme of Your Name is that the future is not predetermined; that fate is something you make for yourself.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_js19hrc",
    parsedId: "js19hrc",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/1503ezn/what_was_the_messagetheme_of_your_name/js19hrc/",
    postId: "t3_1503ezn",
    parentId: "t3_1503ezn",
    username: "OneMoreDuncanIdaho",
    userId: "t2_i31pk",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "Why not read his own words from a recent interview? The interview is about Suzume specifically, but mentions his feelings about Your Name as well.\n&gt;When the disaster happened in 2011... it shook the whole country to the core, myself included. It changed many things. It changed society, and it changed my approach to animation. I gradually started to feel a sense of guilt in making anime. I felt that I wasn't helping anyone if I was simply making anime. The job of creating anime felt useless in helping the earthquake victims. But eventually... I started to explore ways to face and understand disasters that are only possible through anime and entertainment.\n&gt;\n&gt;\n&gt;\n&gt;That led me to making Your Name. and Weathering With You and finally found my way to making Suzume. What I've been feeling in the process of making anime since 2011 is that not just earthquakes, but disasters in general are becoming more common in our lives. We're seeing more disasters. Japan has frequent earthquakes. Aside from earthquakes, the climate crisis is causing extremely heavy rain worldwide. We also experienced a global pandemic.\n\n\n\n&gt;The pandemic started while I was working on Suzume. Our lives are now surrounded by disasters, and it probably won't decrease in number. We need to learn to live side-by-side with disasters. Since 2011, this feeling has grown inside me with each passing year. So it wasn't that I was trying to make a film on natural disasters. But if I wanted to tell a contemporary story, I couldn't avoid the topic. That's how I see it. \n\n\n\n&gt;So with Suzume it started out as the coming-of-age story of a girl, but as I thought about where in Japan she'd travel and how and why she'd grow, I simply couldn't skirt around the topic. It had to be a part of the narrative. That's my honest feeling.\n\nhttps://www.crunchyroll.com/news/interviews/2023/4/28/interview-suzume-director-makoto-shinkai-on-healing-a-wounded-nation-through-anime\n\nThere's also stuff about coming of age and the red string of fate but it's more like a feeling to me that the movie gives than something I could analyze properly.",
    createdAt: "2023-07-15T06:03:44.000Z",
    scrapedAt: "2024-10-13T19:31:26.588Z",
    upVotes: 7,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;Why not read his own words from a recent interview? The interview is about Suzume specifically, but mentions his feelings about Your Name as well.&lt;/p&gt;\n\n&lt;blockquote&gt;\n&lt;p&gt;When the disaster happened in 2011... it shook the whole country to the core, myself included. It changed many things. It changed society, and it changed my approach to animation. I gradually started to feel a sense of guilt in making anime. I felt that I wasn&amp;#39;t helping anyone if I was simply making anime. The job of creating anime felt useless in helping the earthquake victims. But eventually... I started to explore ways to face and understand disasters that are only possible through anime and entertainment.&lt;/p&gt;\n\n&lt;p&gt;That led me to making Your Name. and Weathering With You and finally found my way to making Suzume. What I&amp;#39;ve been feeling in the process of making anime since 2011 is that not just earthquakes, but disasters in general are becoming more common in our lives. We&amp;#39;re seeing more disasters. Japan has frequent earthquakes. Aside from earthquakes, the climate crisis is causing extremely heavy rain worldwide. We also experienced a global pandemic.&lt;/p&gt;\n\n&lt;p&gt;The pandemic started while I was working on Suzume. Our lives are now surrounded by disasters, and it probably won&amp;#39;t decrease in number. We need to learn to live side-by-side with disasters. Since 2011, this feeling has grown inside me with each passing year. So it wasn&amp;#39;t that I was trying to make a film on natural disasters. But if I wanted to tell a contemporary story, I couldn&amp;#39;t avoid the topic. That&amp;#39;s how I see it. &lt;/p&gt;\n\n&lt;p&gt;So with Suzume it started out as the coming-of-age story of a girl, but as I thought about where in Japan she&amp;#39;d travel and how and why she&amp;#39;d grow, I simply couldn&amp;#39;t skirt around the topic. It had to be a part of the narrative. That&amp;#39;s my honest feeling.&lt;/p&gt;\n&lt;/blockquote&gt;\n\n&lt;p&gt;&lt;a href="https://www.crunchyroll.com/news/interviews/2023/4/28/interview-suzume-director-makoto-shinkai-on-healing-a-wounded-nation-through-anime"&gt;https://www.crunchyroll.com/news/interviews/2023/4/28/interview-suzume-director-makoto-shinkai-on-healing-a-wounded-nation-through-anime&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;There&amp;#39;s also stuff about coming of age and the red string of fate but it&amp;#39;s more like a feeling to me that the movie gives than something I could analyze properly.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_js20cf6",
    parsedId: "js20cf6",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/1503ezn/what_was_the_messagetheme_of_your_name/js20cf6/",
    postId: "t3_1503ezn",
    parentId: "t3_1503ezn",
    username: "populist_dogecrat",
    userId: "t2_jytkb6tz",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "You can save your whole game process by just creating a backup. Remember to have a backup.",
    createdAt: "2023-07-15T11:48:58.000Z",
    scrapedAt: "2024-10-13T19:31:26.588Z",
    upVotes: 5,
    numberOfreplies: 1,
    html: '&lt;div class="md"&gt;&lt;p&gt;You can save your whole game process by just creating a backup. Remember to have a backup.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t1_js35x73",
    parsedId: "js35x73",
    url: "https://www.reddit.com/r/KimiNoNaWa/comments/1503ezn/what_was_the_messagetheme_of_your_name/js35x73/",
    postId: "t3_1503ezn",
    parentId: "t1_js20cf6",
    username: "rubikvn2100",
    userId: "t2_z0dsg",
    category: "KimiNoNaWa",
    communityName: "r/KimiNoNaWa",
    body: "Wow, ha ha.",
    createdAt: "2023-07-15T17:20:09.000Z",
    scrapedAt: "2024-10-13T19:31:26.588Z",
    upVotes: 1,
    numberOfreplies: 0,
    html: '&lt;div class="md"&gt;&lt;p&gt;Wow, ha ha.&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
  {
    id: "t3_18pajqr",
    parsedId: "18pajqr",
    url: "https://www.reddit.com/r/anime/comments/18pajqr/this_scene_never_gets_old_your_name/",
    username: "sincereRen",
    userId: "t2_8g7smu65",
    title: "This scene never gets old [Your Name]",
    communityName: "r/anime",
    parsedCommunityName: "anime",
    body: "URL: https://v.redd.it/soqv8rpmx28c1\nThumbnail: spoiler\nImages:\n\thttps://external-preview.redd.it/b2gxbHh4Ynd4MjhjMUzByz-138-bGIAhM8fn64NHycNLd6VbjpxI4HO4s9tY.png?format=pjpg&amp;auto=webp&amp;s=27daeb4a4a3997255b9c371fc52c4cebe4ebf453\n",
    html: null,
    numberOfComments: 116,
    flair: "Clip",
    upVotes: 3180,
    upVoteRatio: 0.97,
    isVideo: true,
    isAd: false,
    over18: false,
    videoUrl: "https://v.redd.it/soqv8rpmx28c1/DASH_1080.mp4?source=fallback",
    thumbnailUrl: "spoiler",
    createdAt: "2023-12-23T17:30:38.000Z",
    scrapedAt: "2024-10-13T19:31:29.390Z",
    dataType: "post",
  },
  {
    id: "t1_kemyzhv",
    parsedId: "kemyzhv",
    url: "https://www.reddit.com/r/anime/comments/18pajqr/this_scene_never_gets_old_your_name/kemyzhv/",
    postId: "t3_18pajqr",
    parentId: "t3_18pajqr",
    username: "meandering_trex",
    userId: "t2_hxefhoqi",
    category: "anime",
    communityName: "r/anime",
    body: "I mean, just the soundtrack in itself is enough to bring me to tears every time I listen to it, and I can't even understand a single word in japanese, it is just so unbelievably good! One of my all-time favorite movies ever!",
    createdAt: "2023-12-23T18:06:26.000Z",
    scrapedAt: "2024-10-13T19:31:29.488Z",
    upVotes: 546,
    numberOfreplies: 3,
    html: '&lt;div class="md"&gt;&lt;p&gt;I mean, just the soundtrack in itself is enough to bring me to tears every time I listen to it, and I can&amp;#39;t even understand a single word in japanese, it is just so unbelievably good! One of my all-time favorite movies ever!&lt;/p&gt;\n&lt;/div&gt;',
    dataType: "comment",
  },
];
